// ============================================================
// BALLOT BUILDER — BALLOT MEASURE DATA
// Auto-generated by output-writer agent
// Generated: 2026-03-11T00:00:00.000Z
// Source: Texas 2026 — Austin TX 78721 ballot
//
// No ballot measures are included for this pipeline run.
//
// Texas does not hold statewide constitutional amendment elections
// in the same cycle as regular general elections — they are held
// in November of odd-numbered years (most recently Nov 2025).
// No state constitutional amendments or binding referenda have
// been confirmed for the Texas November 2026 general election
// ballot as of the scoring date (2026-03-11).
//
// Travis County and City of Austin may place local measures on
// the November 2026 ballot (bond propositions, charter amendments,
// tax rate elections), but these had not been formally noticed or
// certified at the time of this pipeline run and are therefore
// outside scope. Re-run the measure pipeline in August 2026
// after local governing bodies take final action.
// ============================================================

import type { Measure } from '../../../src/server/types/index';

export const ballotMeasures: Measure[] = [];
