// ============================================================
// BALLOT BUILDER — BALLOT MEASURE DATA
// Auto-generated by output-writer agent
// Generated: 2026-02-26T00:00:00.000Z
// Source: North Carolina 2026 — November 3, 2026 General Election
//
// No ballot measures are associated with this contest.
// The NC-US-SENATE-2026 pipeline covers a U.S. Senate race only.
// North Carolina statewide ballot measures for November 2026 are
// determined by the General Assembly and have not yet been referred
// to voters as of this pipeline run date (2026-02-26).
// Re-check after the 2026 legislative session concludes.
// ============================================================

import type { Measure } from '../../src/server/types/index';

export const ballotMeasures: Measure[] = [];
