// ============================================================
// BALLOT BUILDER — CANDIDATE DATA
// Auto-generated by output-writer agent
// Generated: 2026-02-26T00:00:00.000Z
// Source: North Carolina 2026 — Primary: 2026-03-03, Runoff: 2026-05-12, General: 2026-11-03
//
// Contest:
//   NC-US-SENATE-2026 — U.S. Senate, North Carolina (Toss-up)
//   Cook Political Report / Sabato's Crystal Ball / Inside Elections (all three)
//   Open seat — Thom Tillis (R) retiring
//
// Scored candidates (6):
//   roy-cooper        (D) — former Governor, Democratic primary frontrunner
//   michael-whatley   (R) — former RNC Chair, Trump-endorsed GOP frontrunner
//   don-brown         (R) — retired Navy JAG, MAGA-wing challenger
//   michele-morrow    (R) — conservative activist, 2024 Superintendent nominee
//   shannon-bray      (L) — cybersecurity specialist, 4th statewide Libertarian run
//   brian-mcginnis    (G) — Iraq War veteran, firefighter
//
// Skipped (low-evidence, no scored files per pipeline instructions):
//   richard-dansie    (R primary — ~0.4% polling, minimal public profile)
//   thomas-johnson    (R primary — ~1% polling, very limited public profile)
//   elizabeth-temple  (R primary — ~0.6% polling, very limited public profile)
//   robert-colon      (D primary — perennial candidate, no meaningful support)
//   justin-dues       (D primary — long-shot against Cooper, limited record)
//   daryl-farrow      (D primary — long-shot, minimal public profile)
//   alyssia-hammond   (D primary — perennial candidate, no meaningful support)
//   shaunesi-deberry  (unaffiliated general — limited infrastructure/fundraising)
// ============================================================

import type { Candidate } from '../../src/server/types/index';

export const candidates: Candidate[] = [

  // ── NC-US-SENATE-2026 — U.S. Senate, North Carolina ────────────────────────
  // Primary: 2026-03-03 | Runoff: 2026-05-12 | General: 2026-11-03
  // Race rating: Toss-up (Cook Political Report / Sabato's Crystal Ball / Inside Elections)
  // Open seat — Thom Tillis (R) retiring
  // Cooper (D) leads Whatley (R) by +6 in Emerson polling (Jan 2026)
  {
    id: 'roy-cooper',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Roy Cooper',
      ballotDisplay: 'Roy Cooper',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 1,
    profileSummary: 'Former two-term North Carolina Governor (2017-2025) and six-time statewide winner with 38+ years in public office; a center-left pragmatist who expanded Medicaid, signed landmark clean energy legislation, and used the veto pen extensively against a Republican supermajority on guns, vouchers, and abortion.',
    positions: [
      'Signed Medicaid expansion covering 600,000+ North Carolinians; defends ACA subsidies and Medicare',
      'Signed HB 951 mandating 70% carbon reduction by 2030 and carbon neutrality by 2050 — first purple-state governor to sign an emissions mandate into law',
      'Vetoed multiple gun bills including pistol permit repeal and permit-to-purchase repeal; created statewide Office of Violence Prevention',
      'Vetoed $6B+ school voucher expansion; strong pro-public school position throughout governorship',
      'Commuted 15 death row sentences (largest clemency action in NC history) while maintaining death penalty is "appropriate in certain heinous cases"',
    ],
    axisStances: {
      econ_safetynet:            2, // HIGH — Medicaid expansion for 600K, teacher pay, $15/hr state employee minimum wage, 2026 campaign opposes "cutting help for the poor"
      econ_investment:           3, // MEDIUM — consistent public investment orientation; signed compromise budgets with R legislature; not a GND-scale spender
      econ_tax_structure:        3, // MEDIUM — vetoed broad corporate/income tax cuts; called for freezing high-income cuts for education revenue; signed 2021 budget beginning corporate tax phaseout (pragmatic compromise)
      econ_school_choice:        2, // HIGH — vetoed HB 10 ($6B+ voucher expansion, 2024); "sending taxpayer dollars to private schools with no accountability"
      health_coverage_model:     3, // HIGH — signed Medicaid expansion; defends ACA subsidies; no evidence of Medicare for All or public option endorsement; expand-existing-programs position
      housing_affordability_tools: 3, // LOW — proposed $160M affordable housing investment (2019); single data point; government-subsidy orientation
      justice_policing_accountability: 3, // HIGH — created TREC (Task Force for Racial Equity in Criminal Justice, 2020); signed SB 300 reform package: duty to intervene, early intervention, diversity recruitment
      justice_sentencing_goals:  3, // HIGH — commuted 15 death row sentences (Dec 2024, largest in NC history); signed First Step Act-related reforms; not abolitionist
      justice_firearms:          2, // HIGH — vetoed SB 41 (permit-to-purchase repeal, 2023); vetoed HB 398 (pistol permit repeal, 2021); created Office of Violence Prevention; NRA opposition
      climate_ambition:          2, // HIGH — EO 80 (40% GHG reduction by 2025); signed HB 951 (70% by 2030, neutral by 2050); EO 246 (50% by 2030); LCV Action Fund endorsement 2026
      climate_energy_portfolio:  3, // HIGH — HB 951 bipartisan clean energy targets with Duke Energy; NC #9 nationally in clean energy jobs; transition framing, not fossil fuel ban
    },
    valueStances: {
      universalism:   0.6,  // Strong environmental record (EO 80, HB 951, EO 246); Medicaid expansion; DACA support; HB2 compromise repeal; pragmatic limits temper ceiling
      benevolence:    0.7,  // Medicaid for 600K, teacher pay, $15/hr minimum, Office of Violence Prevention, criminal justice reform; rhetoric centers on "working families"
      tradition:     -0.2,  // Commuted death row vs. NC tradition; repealed HB2; vetoed 12-week abortion ban; works within institutions despite challenges
      conformity:     0.6,  // 38+ years of public service; used constitutional veto power (not overreach); signed compromise bills; institutional process adherence
      security:       0.5,  // Economic security through Medicaid/safety net; community safety via Office of Violence Prevention and policing reform (not defund)
      power:          0.1,  // DSCC-backed establishment; vetoed corporate tax cuts; $930M+ in targeted corporate incentives tempers score; pragmatic relationship with power
      achievement:    0.3,  // Workforce development through clean energy jobs; teacher pay and training investment; personal achievement (six-time statewide winner) secondary to collective rhetoric
      hedonism:       0.0,
      stimulation:   -0.1,  // Establishment figure with 38+ years in NC politics; steady, institutional, incremental governance style
      self_direction: 0.4,  // Pro-choice (SB 20 veto); LGBTQ+ rights (HB2 repeal); DACA support; gun regulations and emissions mandates are counterweight
    },
    // Scoring notes
    // - Tax policy: pragmatic compromises (2021 corporate phaseout, $930M+ incentives) temper econ_tax_structure score; directional lean is progressive
    // - School choice: policy position (anti-voucher) scored, not personal choice (sent children to private school)
    // - Death penalty: evolution from AG (supervised 27 executions) to Governor (commuted 15 sentences); scored on current/recent position per recency rule
    // - HB2 compromise: LGBTQ+ advocates criticized the 2017 repeal as insufficient (included moratorium on local nondiscrimination ordinances); reflects supermajority constraints
    // - Immigration: vetoed 3+ ICE cooperation bills and signed DACA support letter, but also signed one bill FLOC-AFL-CIO called "anti-immigrant, anti-worker"
    // - Axes skipped (no meaningful evidence): health_cost_control, health_public_health, housing_supply_zoning, housing_transport_priority, climate_permitting
  },

  {
    id: 'michael-whatley',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Michael Whatley',
      ballotDisplay: 'Michael Whatley',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 2,
    profileSummary: 'Former RNC Chair and fossil fuel industry lobbyist with no prior elected office; Trump-endorsed frontrunner for the NC GOP Senate nomination running on energy deregulation, immigration enforcement, and DOGE-style spending cuts.',
    positions: [
      'All-of-the-above energy including carbon; decade of fossil fuel industry advocacy at Consumer Energy Alliance opposing emission rules and fracking regulations',
      'Supports DOGE-style federal spending cuts, Medicaid work requirements, and deficit reduction as top priority',
      'Back the blue; eliminate sanctuary cities; full ICE cooperation and mass deportation support',
      'Celebrated Dobbs; supported NC 12-week abortion ban; backed GOP platform with no-exceptions ban language',
      'No-tax-on-tips, no-tax-on-overtime, no-tax-on-Social Security; aligns with Trump tax cut agenda',
    ],
    axisStances: {
      econ_safetynet:            8, // MEDIUM — Medicaid work requirements, purging undocumented immigrants from Medicaid, DOGE-style cuts; "national deficit is one of the biggest threats America faces"
      econ_investment:           8, // MEDIUM — strong DOGE support; deregulatory career background; opposition to "woke" spending; entire professional career in fossil fuel industry deregulation advocacy
      econ_tax_structure:        7, // MEDIUM — no-tax-on-tips, no-tax-on-overtime, no-tax-on-Social Security; populist tax cuts that reduce revenue without progressive redistribution
      health_coverage_model:     7, // LOW — supports Medicaid work requirements; removing undocumented from Medicaid; DOGE framing implies market-oriented direction; no explicit ACA repeal found
      health_public_health:      9, // MEDIUM — "We don't need separation of faith and politics. We don't need separation of church and state" (pastor summit); anti-transgender mandates; strong individual liberty framing
      justice_policing_accountability: 9, // MEDIUM — "Back the blue every day"; supports eliminating sanctuary cities; attacks Cooper as soft on crime; full ICE cooperation; no accountability reform language found anywhere
      justice_sentencing_goals:  8, // LOW — attacks Cooper as "soft on crime"; "safe communities" central campaign pillar; absence of any rehabilitation language implies punishment/deterrence; inferred from framing
      justice_firearms:          8, // LOW — no NRA grade (no legislative record); no explicit firearms statements; Trump endorsement, "back the blue" orientation, and absence of gun regulation language strongly imply pro-2A; inferred from alignment
      climate_ambition:          9, // HIGH — 11 years as EVP/co-founder of Consumer Energy Alliance (funded by BP, Chevron, ExxonMobil, Marathon, Shell, Statoil); opposed low-carbon fuel standards, fracking regs, power plant emission rules; 2026 campaign: "all-of-the-above including carbon"
      climate_energy_portfolio:  8, // HIGH — career advocating offshore Atlantic drilling (including off NC coast); opposing renewable energy mandates and emission regulations; "all-of-the-above including carbon" masks strong fossil fuel preference per career record
      climate_permitting:        9, // MEDIUM — decade of CEA advocacy focused on reducing permitting barriers for fossil fuel projects (offshore drilling, pipelines, fracking); DOGE-style deregulation framing extends this orientation
    },
    valueStances: {
      universalism:  -0.6,  // Active opposition to environmental protection through decade of fossil fuel advocacy; mass deportation focus; "all-of-the-above including carbon" prioritizes extraction over environmental welfare
      benevolence:    0.2,  // Weak positive: "safe communities" messaging; WNC roots; but care is narrowly scoped to law enforcement rather than social services
      tradition:      0.8,  // Explicit rejection of church-state separation at pastor summit; celebrated Dobbs; anti-transgender mandates; NC GOP platform alignment; religious values in governance is central and consistent
      conformity:    -0.3,  // As RNC Chair, promoted false 2020 election fraud claims (CNN KFile); significant norm violation on fundamental democratic process; generally defers to party hierarchy
      security:       0.7,  // "Safe communities" as campaign pillar; back the blue; eliminate sanctuary cities; ICE cooperation; border security emphasis; defining campaign theme
      power:          0.6,  // Career alignment with fossil fuel industry (BP, Chevron, ExxonMobil, Shell as CEA funders); national party chair; Trump endorsement; NRSC backing; $6.27M raised
      achievement:    0.4,  // Work requirements imply meritocratic orientation; career trajectory from congressional staffer to industry EVP to RNC chair; "strong economy" messaging
      hedonism:      -0.3,  // Rejection of church-state separation and anti-transgender mandates restrict personal lifestyle liberty; social conservatism actively works against hedonism
      stimulation:   -0.2,  // Establishment orientation — rose through party ranks, chaired RNC, represents institutional Republican power; DOGE framing is disruption in service of restoration, not innovation
      self_direction:-0.1,  // Pro-individual-liberty on public health (opposing mandates); but Dobbs celebration, no-exceptions abortion platform, and immigration enforcement restrict others' autonomy; net slightly negative
    },
    // Scoring notes
    // - Energy framing conflict: "all-of-the-above including carbon" sounds balanced, but 11-year CEA career was exclusively fossil fuel advocacy funded by BP, Chevron, ExxonMobil, Shell, Marathon, and Statoil. Career record treated as behavioral evidence per voting-record-over-stated-position rule. climate_energy_portfolio scored at 8, not the 5 that "all-of-the-above" alone would warrant.
    // - Election integrity: promoted false 2020 election fraud claims as RNC Chair (CNN KFile 2024); now runs on "election integrity" platform framed around voter ID. Affects conformity value score.
    // - Abortion framing: publicly calls NC 12-week ban "responsible, reasonable, and mainstream" while supporting NC GOP platform with no-exceptions language. Platform treated as stronger signal; health_reproductive not a scored civic axis but noted here for transparency.
    // - All scores based on stated positions and career record — no legislative voting history exists. Firearms position inferred from alignment (LOW confidence).
    // - Axes skipped (no direct evidence): econ_school_choice, housing_supply_zoning, housing_affordability_tools, housing_transport_priority, health_cost_control
  },

  {
    id: 'don-brown',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Don Brown',
      ballotDisplay: 'Don Brown',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 3,
    profileSummary: 'Retired Navy JAG officer and January 6 defense attorney running a long-shot MAGA-wing Senate bid; platforms on eliminating the IRS, banning vaccine mandates, Constitutional Carry, and aggressive deficit reduction.',
    positions: [
      'Eliminate the IRS and replace income tax with a national consumption tax (FairTax) supplemented by tariffs',
      'Ban all vaccine and mask mandates federally via proposed "Vax and Mask Freedom Act"; personally litigated against COVID vaccine mandates',
      'National Constitutional Carry; opposes all gun regulations; "Americans should not be arrested for exercising our clear 2nd Amendment Rights to bear arms without restriction"',
      'Personhood from conception; supports federal death penalty for fentanyl and child sex traffickers',
      'Reduce federal spending to attack the $38 trillion national debt; route disaster relief through private/faith-based channels (Samaritan\'s Purse)',
    ],
    axisStances: {
      econ_safetynet:            9, // MEDIUM — "restoring fiscal sanity"; attacks $38T national debt; proposes routing disaster relief through Samaritan's Purse rather than federal agencies; no support for any safety net expansion
      econ_investment:           9, // MEDIUM — frames government as "regulatory strangulation" of small business; deregulation as primary economic tool; proposes privatizing disaster relief
      econ_tax_structure:       10, // MEDIUM — wants to eliminate the IRS entirely, abolish the federal income tax, replace with FairTax (national consumption tax) plus tariffs; most extreme Pole B position on this axis
      health_coverage_model:     9, // MEDIUM — does not see an "affordability crisis" in healthcare; supports HSA-style direct payments; no support for ACA, public option, Medicaid expansion, or Medicare expansion
      health_cost_control:       8, // LOW — no direct statement on drug pricing or hospital rate-setting; inferred from overall market-first healthcare philosophy and denial of affordability crisis
      health_public_health:     10, // HIGH — proposed "Vax and Mask Freedom Act" to ban all vaccine and mask mandates federally; personally litigated against COVID vaccine mandates for nuclear engineers; multiple corroborating sources
      housing_affordability_tools: 8, // LOW — proposed eliminating property taxes for first-time homebuyers (tax-cut approach, not subsidies); no support for public housing, rent stabilization, or housing subsidies
      justice_policing_accountability: 9, // MEDIUM — called for National Guard on every Charlotte train; attacked Cooper for releasing pandemic-era inmates; supports aggressive Border Patrol enforcement; strong law-and-order positioning
      justice_sentencing_goals:  9, // MEDIUM — supports federal death penalty for fentanyl traffickers and child sex traffickers; attacks opponents as "soft on crime"; no mention of rehabilitation or diversion
      justice_firearms:         10, // HIGH — supports National Constitutional Carry; "Americans should not be arrested for exercising our clear 2nd Amendment Rights to bear arms without restriction"; opposes all gun regulations
    },
    valueStances: {
      universalism:  -0.6,  // No evidence of concern for welfare of all people or nature; endorsement network (Robinson, Flynn, Powell) signals strong in-group orientation; denial of healthcare affordability crisis
      benevolence:    0.2,  // Some community framing: small business protection, Hurricane Helene relief via Samaritan's Purse, defending J6 defendants; scope is narrow and ideological
      tradition:      0.8,  // Personhood-from-conception rooted in religious values; faith-based disaster relief preference; military service and patriotic framing; defense of "patriot" J6 defendants
      conformity:    -0.5,  // Despite law-and-order rhetoric, actively defended J6 defendants and called prosecutions "illegal fedsurrection"; endorsed by Sidney Powell (guilty plea) and Michael Flynn; rejects institutional processes when ideologically inconvenient
      security:       0.6,  // Military background (Navy JAG); aggressive border enforcement; National Guard deployment proposals; "tough on crime"; death penalty advocacy; oriented toward physical/national security, not economic security
      power:          0.3,  // Not aligned with corporate donor class ($187K raised, $24K cash on hand); policies favor economic power holders (eliminate IRS, deregulate, market healthcare); strong executive/enforcement framing
      achievement:    0.5,  // Self-reliance framing throughout; small business protection; market-based healthcare; opposition to government dependency; military career; author of 16 books
      hedonism:      -0.1,  // Anti-mandate positions touch on personal freedom but framed as liberty/self-direction; personhood-from-conception works modestly against lifestyle liberty; near-neutral
      stimulation:    0.5,  // Genuinely radical proposals: eliminate the IRS, FairTax, Vax and Mask Freedom Act, National Guard on trains, privatize disaster relief; insurgent against party establishment
      self_direction: 0.4,  // Strong on gun rights as individual liberty, anti-mandate positions; personhood-from-conception restricts reproductive autonomy; selective application of liberty produces moderate net positive
    },
    // Scoring notes
    // - Law and order vs. J6 defense: positions himself as "law and order" candidate while defending J6 defendants and calling prosecutions "illegal fedsurrection." Scored justice_policing_accountability at 9 on weight of stated positions on crime; J6 defense reveals selective application of law-and-order principles. Reflected in conformity value score of -0.5.
    // - Fiscal hawk vs. targeted spending: campaigns on $38T debt reduction but proposes dedicated Hurricane Helene trust fund and property tax elimination for first-time homebuyers. Resolved via private/faith-based channels framing and tax-cut classification (consistent with anti-government philosophy).
    // - Axes skipped (no evidence found): econ_school_choice, housing_supply_zoning, housing_transport_priority, climate_ambition, climate_energy_portfolio, climate_permitting
  },

  {
    id: 'michele-morrow',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Michele Morrow',
      ballotDisplay: 'Michele Morrow',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 4,
    profileSummary: 'Conservative activist and former homeschool educator with no legislative record; best known for her 2024 Superintendent of Public Instruction campaign centered on school choice, medical freedom, and anti-establishment rhetoric. Extensive controversy record including calls for political violence and conspiracy theory promotion.',
    positions: [
      'Universal school choice advocate: supports vouchers, opposes public school "monopoly," launched school choice lobbying group after losing 2024 Superintendent race',
      'Anti-vaccine mandate activist; called COVID vaccine "population control"; "medical freedom" is a core campaign theme',
      'Replace ACA with market-based healthcare and health savings accounts',
      'Hardline immigration: mass deportation, self-deportation programs',
      'Strongly pro-2A: supports arming teachers; no gun safety or regulation positions found in any source',
    ],
    axisStances: {
      econ_safetynet:        8, // MEDIUM — anti-spending rhetoric; no support for any safety net expansion; directional signal without specific policy proposals
      econ_school_choice:    9, // HIGH — signature issue; ran for NC Superintendent of Public Instruction on school choice platform; supports vouchers, parental choice, competition model; called public school teachers "groomers"; launched lobbying group post-2024 loss
      health_coverage_model: 8, // MEDIUM — stated position: replace ACA with market-based solutions and health savings accounts; no nuance or caveats found
      health_public_health: 10, // HIGH — called COVID vaccine "population control"; anti-vaccine mandate activism is central to her public identity; "medical freedom" is a defining campaign theme; multiple independent sources confirm; most extreme anti-public-health-mandate position on the scale
      justice_firearms:      9, // MEDIUM — broad 2nd Amendment support including arming teachers; no gun safety or regulation positions found in any source; scored 9 (not 10) because no explicit advocating for permitless carry or eliminating all existing regulations
    },
    valueStances: {
      universalism:  -0.8,  // Hardline anti-immigrant stance (mass deportation); QAnon promotion; #DeathtoTraitors rhetoric; called for Obama's execution; explicitly exclusionary political identity
      benevolence:   -0.1,  // Claims to advocate for children and parents through school choice, but framing is combative; calls public school teachers "groomers"; anti-vaccine activism works against community health; care is narrowly scoped to ideological in-group
      tradition:      0.8,  // NC Values Coalition endorsed; strongly anti-abortion; traditional family values and religious values in governance central to identity; homeschool advocacy rooted in traditional family structure
      conformity:    -0.9,  // Called for public execution of a former president; urged Trump to "put the Constitution to the side" and invoke the Insurrection Act; attended January 6 rally; used #DeathtoTraitors hashtag 12 times; promoted QAnon; fundamental rejection of democratic institutional norms
      security:       0.3,  // Border security and national defense framing (positive); January 6 participation and calls for political violence are fundamentally destabilizing (negative); competing signals partially cancel
      power:          0.3,  // Aligns with MAGA power structure; minimal fundraising ($10,720 raised) and low polling (1.6-4%) prevent higher score; aspiration more than demonstrated power alignment
      achievement:    0.3,  // Self-reliance framing through homeschool advocacy; individual effort and parental responsibility emphasis; school choice as enabling individual achievement
      hedonism:      -0.2,  // Social conservatism on personal behavior (anti-abortion, traditional family values); anti-vaccine position is conspiracy-based rather than liberty-based
      stimulation:    0.5,  // Strongly anti-establishment; defeated Republican incumbent Truitt in 2024 Superintendent primary; explicitly revolutionary and disruptive rhetoric; but disruption aimed at restoring perceived past order
      self_direction: 0.4,  // Strong on school choice as parental autonomy, gun rights, anti-vaccine mandates as medical freedom; anti-abortion restricts others' bodily autonomy; selective application of liberty
    },
    // Scoring notes
    // - Conformity vs. security tension: frames herself as pro-security while calling for political executions and urging suspension of the Constitution — fundamentally incompatible. conformity scored at -0.9; security moderated to 0.3.
    // - Self-direction is applied selectively to in-group freedoms only (school choice, gun rights, medical freedom for supporters; restricts reproductive autonomy and deports immigrants).
    // - Only 5 of 16 civic axes scored — most platform coverage is education, healthcare freedom, firearms, and immigration. 11 axes skipped due to complete absence of evidence.
    // - Axes skipped (no evidence found): econ_investment, econ_tax_structure, health_cost_control, housing_supply_zoning, housing_affordability_tools, housing_transport_priority, justice_policing_accountability, justice_sentencing_goals, climate_ambition, climate_energy_portfolio, climate_permitting
  },

  {
    id: 'shannon-bray',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Shannon Bray',
      ballotDisplay: 'Shannon Bray',
    },
    party: 'Libertarian',
    incumbencyStatus: 'challenger',
    ballotOrder: 5,
    profileSummary: 'Perennial Libertarian candidate (4th statewide race since 2020) with a cybersecurity background and Navy veteran status; presents an unusually detailed platform combining extreme free-market economics with strong civil liberties positions on policing and criminal justice.',
    positions: [
      'Abolish the IRS and replace income tax with FairTax (national sales tax); phase out Social Security by 2035',
      'Repeal the ACA; replace with health savings accounts and patient data ownership',
      'Abolish qualified immunity, end civil asset forfeiture, ban no-knock warrants',
      'Full drug legalization and abolish the federal death penalty',
      'Repeal existing gun regulations; strong Second Amendment absolutist',
    ],
    axisStances: {
      econ_safetynet:            10, // HIGH — explicit plan to phase out Social Security by 2035; most extreme Pole B position on this axis; consistent across all 4 campaign cycles (2020-2026)
      econ_investment:            9, // HIGH — opposes government subsidies and industrial policy; consistent anti-subsidy stance across all campaigns; LPNC platform alignment
      econ_school_choice:         8, // HIGH — supports school choice, vouchers, and competition; LPNC platform; consistent position 2024-2026; clear direction without granular plan
      econ_tax_structure:        10, // HIGH — FairTax/abolish the IRS is the defining policy position of his candidacy; detailed treatment in book "Liberty Unleashed"; consistent across all 4 cycles and multiple interviews
      health_coverage_model:      9, // HIGH — explicit ACA repeal; proposes HSAs and patient data ownership as replacement; scored 9 (not 10): data ownership approach involves systemic reform rather than pure laissez-faire
      health_cost_control:        9, // MEDIUM — opposes government intervention in healthcare markets broadly; patient data ownership framing suggests market transparency as cost-control mechanism; inferred from philosophy (no specific drug-pricing statement)
      health_public_health:       9, // HIGH — strong individual choice framing on all public health mandates; consistent since 2020 (COVID was formative for his first Senate campaign); scored 9: clear anti-mandate but does not explicitly advocate eliminating all public health infrastructure
      housing_affordability_tools: 9, // LOW — inferred from comprehensive anti-subsidy, anti-government-intervention philosophy; no housing-specific affordability statement found; philosophical inference, not stated housing position
      justice_policing_accountability: 2, // HIGH — abolish qualified immunity, end civil asset forfeiture, ban no-knock warrants; strong Pole A reform position; notable contrast with extreme Pole B economic positions; scored 2 (not 0-1): does not advocate defunding or abolishing police
      justice_sentencing_goals:   1, // HIGH — full drug legalization (not just decriminalization) and abolishing the federal death penalty; rooted in individual liberty rather than rehabilitation framing, but outcome aligns strongly with Pole A
      justice_firearms:          10, // HIGH — supports repealing existing gun regulations; Second Amendment absolutist; most extreme Pole B position: not merely opposing new restrictions but seeking to repeal existing ones
      climate_ambition:           9, // HIGH — explicitly opposes carbon taxes; wants to slash energy regulations; scored 9 (not 10): opposes climate policy intervention but does not appear to deny climate science outright
      climate_energy_portfolio:   8, // HIGH — pro-nuclear, anti-clean-energy-subsidy; scored 8 (not 9-10): support for nuclear power represents acceptance of low-carbon technology; objection is to subsidies and mandates, not clean energy per se
      climate_permitting:         8, // MEDIUM — no specific permitting reform statement; inferred from comprehensive deregulation philosophy; would almost certainly favor faster approvals and reduced environmental review
    },
    valueStances: {
      universalism:   0.1,  // Justice reform positions (end qualified immunity, drug legalization, abolish death penalty) reflect concern for equal treatment — universalist impulse; economic positions (eliminate safety net, repeal ACA) disproportionately affect vulnerable populations; equal liberty rather than equal outcomes
      benevolence:   -0.1,  // Navy service and repeated candidacy suggest some community care; policy positions consistently prioritize individual choice over collective care mechanisms; does not frame issues as helping vulnerable; not actively hostile but does not prioritize
      tradition:     -0.2,  // Policy positions are radical departures from established systems (abolish IRS, replace income tax, legalize drugs, restructure Social Security); invokes founding-era limited government tradition as counterweight; net slightly negative
      conformity:    -0.6,  // Runs as third-party candidate despite near-certain loss (direct challenge to two-party norms); proposes repealing existing laws and abolishing established institutions; drug legalization and anti-mandate positions reject social control; entire political project is about removing constraints
      security:      -0.5,  // Policy positions systematically oppose security-oriented interventions: phase out Social Security, repeal ACA, oppose public health mandates, drug legalization; Navy veteran and cybersecurity professional (security-adjacent) but political identity prioritizes liberty over safety at virtually every decision point
      power:         -0.3,  // Actively works to dismantle governmental power structures: abolish IRS, end qualified immunity, reduce federal authority; seeks elected office to reduce the power of the office itself; net negative: running to reduce institutional power, not to wield it
      achievement:    0.3,  // Navy veteran, master's degree, career at Visa and Microsoft, published author; persistent candidacy despite repeated losses; drive and personal standards; achievement is not the defining rhetorical frame (liberty is)
      hedonism:       0.2,  // Drug legalization implies tolerance for personal pleasure-seeking; "live and let live" philosophy; incidental to liberty framework rather than standalone motivation
      stimulation:    0.5,  // 4th statewide candidacy with radical proposals (FairTax, drug legalization, abolish IRS, phase out Social Security); cybersecurity background at leading edge of technological change; appetite for disruption evident
      self_direction: 0.9,  // Individual liberty is the foundational and defining principle of his entire political identity; every policy position is framed through the lens of independent choice and action; most central value, consistent across 4 campaigns, a book, and extensive policy documentation
    },
    // Notable pattern: Bray presents a distinctive libertarian cross-axis profile — extreme Pole B on all economic axes (9-10), all health axes (9), and climate axes (8-9), combined with strong Pole A on justice/policing (2) and sentencing (1), while being extreme Pole B on firearms (10). This scatter will not match cleanly with either progressive or conservative user profiles — produces uniquely high matches with users who combine economic conservatism with civil libertarian justice positions.
    // Axes skipped (no Bray-specific statements): housing_supply_zoning, housing_transport_priority (zoning is additionally ambiguous for libertarians — deregulating zoning is Pole A in outcome but Pole B in philosophy of removing government)
  },

  {
    id: 'brian-mcginnis',
    contestId: 'NC-US-SENATE-2026',
    name: {
      full: 'Brian McGinnis',
      ballotDisplay: 'Brian McGinnis',
    },
    party: 'Other', // Green Party — 'Green' is not in the Party union type
    incumbencyStatus: 'challenger',
    ballotOrder: 6,
    profileSummary: 'First-time Green Party candidate; Iraq War veteran and active firefighter running on an anti-war, pro-social-services platform with no prior elected office or legislative record.',
    positions: [
      'Anti-war foreign policy: opposes "wars based on greed," calls for military restraint to imminent national security threats only',
      'Increased public education funding; opposes federal cuts to schools',
      'Solar energy investment in rural NC communities; supports manufacturing revival',
      'Expanded and better-staffed VA for veterans; advocates for improved veteran care',
      'No corporate donations; term limits; pledges to serve only one term',
    ],
    axisStances: {
      econ_safetynet:          2, // LOW — "anti war, pro social services perspective"; VA staffing and access expansion; Green Party platform (expand all safety net programs, UBI, universal childcare); personal statements are directionally clear but lack specifics
      econ_investment:         2, // LOW — "ramping up manufacturing and energy in NC with furniture and other factories, as well as solar farms"; education system "in dire need of increased funding instead of federal cuts"; VA "needs to be better staffed"; consistent public investment direction
      econ_school_choice:      1, // MEDIUM — education system "in dire need of increased funding instead of federal cuts" (personal); Green Party platform: "fully fund public schools; oppose vouchers; oppose privatization and for-profit charter schools"
      econ_tax_structure:      2, // LOW — no-corporate-donations pledge signals anti-corporate orientation; Green Party platform: "highly progressive taxation; shift tax burden to corporations; tax wealth and speculation"; no personal statement on tax policy
      health_coverage_model:   1, // LOW — "pro social services" consistent but not specific; Green Party platform: "Medicare for All / single-payer universal healthcare; eliminate private insurance role"; McGinnis has not personally articulated this position
      health_cost_control:     2, // LOW — entirely inferred from Green Party platform position on single-payer healthcare, which implies government price controls; no personal statement on drug pricing or hospital rate-setting
      climate_ambition:        1, // LOW — personal advocacy for solar farms in rural NC; Green Party platform: "Green New Deal — WWII-scale mobilization; 100% clean renewable energy by 2030; end new fossil fuel development"; personal evidence weakly corroborates full ambition level
      climate_energy_portfolio: 1, // MEDIUM — personal statement specifically advocates for solar energy investment; Green Party platform: 100% renewables and ending fossil fuel development; personal solar advocacy directly corroborates platform's renewables-first direction
      housing_affordability_tools: 1, // LOW — entirely platform-derived; Green Party platform: "housing as a human right; rent control with vacancy control; public housing investment"; no personal statement on housing affordability
      housing_transport_priority: 2, // LOW — entirely platform-derived; Green Party platform: "mass transit expansion; reduce car dependence"; McGinnis's emphasis on rural NC economies may complicate transit-first position (rural areas are inherently more car-dependent)
      justice_policing_accountability: 2, // LOW — entirely platform-derived; Green Party platform: "demilitarize police; independent civilian review boards"; McGinnis's firefighter and military background could plausibly cut either direction; insufficient personal evidence
      justice_sentencing_goals: 2, // LOW — entirely platform-derived; Green Party platform: "end war on drugs; oppose mandatory minimums; end mass incarceration"; no personal statement on sentencing or criminal justice
      justice_firearms:        1, // LOW — entirely platform-derived; Green Party platform: "ban on assault weapons; universal background checks; firearms safety course requirement"; as a Marine veteran and firefighter, McGinnis may have personal views that diverge — no evidence either way
    },
    valueStances: {
      universalism:   0.5,  // Anti-war stance rooted in opposition to exploitation ("wars based on greed"); pro-Palestine advocacy with firsthand West Bank witness account; solar energy in economically disadvantaged rural areas; "pro social services" framing; specific rather than abstract universalism
      benevolence:    0.6,  // Active firefighter — career defined by caring for community members in crisis; VA advocacy rooted in personal veteran experience; education funding framed as addressing community need; in-group care orientation is textbook benevolence
      tradition:     -0.2,  // Running as Green Party candidate against two-party system; advocating structural changes to energy and education; opposing conventional foreign policy; but military service and firefighter identity show traditional orientation
      conformity:    -0.3,  // Third-party candidacy is inherently non-conformist; rejection of corporate donations rejects accepted political norms; one-term pledge rejects career politician norms; anti-war stance dissents from bipartisan foreign policy consensus
      security:       0.1,  // Military service and firefighting suggest comfort with security-oriented institutions; anti-war stance and critique of military overuse work against traditional security framing; VA advocacy is security-adjacent; near-neutral
      power:         -0.4,  // Explicit rejection of corporate power and influence in politics; anti-war stance frames military action as serving elite interests ("wars based on greed"); one-term pledge and no-corporate-donations pledge actively renounce power-accumulation strategies; platform redistributes from powerful to less powerful
      achievement:    0.0,  // No meaningful signal in either direction; rhetoric not framed around personal accomplishment or competitive success; Marine service and firefighting career show competence but are not rhetorically framed as achievements
      hedonism:       0.0,  // No evidence in either direction; campaign rhetoric is entirely about service, policy, and justice
      stimulation:    0.2,  // Willingness to challenge the political status quo through Green Party run; rhetoric is more about returning to fundamentals (better-staffed VA, more school funding) than bold experiments; Iraq War service and West Bank visit show engagement with challenging experiences
      self_direction: 0.4,  // Running as third-party candidate against two-party system is expression of independent thought; rejection of corporate donations signals resistance to institutional influence; one-term pledge suggests desire to act freely rather than optimize for re-election
    },
    // Almost all axis scores are LOW confidence due to first-time candidacy with minimal campaign presence (gp.org page, one podcast appearance, Instagram posts) and near-complete reliance on Green Party platform rather than personal statements.
    // As a Marine veteran and firefighter, McGinnis may have personal firearms views that diverge from the Green Party platform — this is a significant evidence gap.
    // Axes skipped (no personal or platform statement specific enough): health_public_health, housing_supply_zoning, climate_permitting
  },

];
