// ============================================================
// BALLOT BUILDER — BALLOT MEASURE DATA
// Auto-generated by output-writer agent
// Generated: 2026-02-27T12:00:00.000Z
// Source: Texas 2026 — Primary: 2026-03-03, General: 2026-11-03
//
// No ballot measures are included for this pipeline run.
//
// The March 3, 2026 Republican and Democratic primaries include
// non-binding advisory propositions, but these are party internal
// preference polls — not official state ballot measures — and
// are outside the scope of this pipeline. No state constitutional
// amendments or binding referenda have been confirmed for the
// Texas general election as of the scoring date (2026-02-27).
// ============================================================

import type { Measure } from '../../../src/server/types/index';

export const ballotMeasures: Measure[] = [];
