// ============================================================
// BALLOT BUILDER — BALLOT MEASURE DATA
// Auto-generated by output-writer agent
// Generated: 2026-02-26T00:00:00.000Z
// Source: Georgia 2026 — November 3, 2026 General Election
//
// Only confirmed measures are included.
// Pending measures (timber tax exemption, probate judge nonpartisan,
// homestead tax elimination, affordable housing classification) are
// excluded — re-check after 2026-03-06 (Crossover Day) to see
// which cleared both chambers and should be added.
// ============================================================

import type { Measure } from '../../src/server/types/index';

export const ballotMeasures: Measure[] = [

  {
    id: 'ga-2026-conservation-use-acreage',
    type: 'measure',
    title: 'Georgia Increase Maximum Acreage of Bona Fide Conservation Use Property Amendment (2026)',
    shortTitle: 'Conservation Use Property Acreage Increase',
    description:
      'Shall the Constitution of Georgia, for the purpose of protecting family farmland, be amended so as to increase the maximum acreage to qualify for assessment and taxation as a bona fide conservation use property from 2,000 acres to 4,000 acres?',
    // Effect of a YES vote on each axis.
    // Score toward 0 = YES vote is more progressive/interventionist (poleA).
    // Score toward 10 = YES vote is more conservative/market-oriented (poleB).
    yesAxisEffects: {
      econ_tax_structure: 7,      // MEDIUM — expands a preferential property tax assessment benefiting largest landowners (2,000+ acres); shifts some local tax burden to other taxpayers
      housing_supply_zoning: 6,   // LOW — indirect: CUVA strengthens incentive to keep large parcels in agricultural/conservation use rather than selling for development; not a zoning measure
    },
    yesValueEffects: {
      tradition: 0.5,     // Explicitly framed as "protecting family farmland"; expands 35-year-old program (CUVA, est. 1990); Senate study committee named "Preservation of Georgia's Farmlands"
      security: 0.4,      // Promotes stability of rural land use; keeps agricultural land in production; 10-year covenant requirement provides long-term stability guarantees; modestly supports food security
      conformity: 0.3,    // Followed proper institutional channels: Senate study committee with hearings in 5 cities, near-unanimous passage (168-5 House, 50-1 Senate); incremental expansion of existing program
      power: 0.3,         // Primary beneficiaries are landowners with 2,000+ acres — relatively wealthy, asset-rich class; "family farmland" ballot language does not restrict benefits to family farms; timber companies and agribusiness also benefit
      benevolence: 0.2,   // Legislative framing emphasizes preserving rural communities and farm families; actual mechanism benefits the largest landowners (not typical family-scale farmers); rhetoric vs. narrow beneficiary class
      achievement: 0.2,   // Supports economic viability of large-scale agricultural operations; study committee framed issue as farms needing to grow larger to remain "economically viable"
      universalism: 0.1,  // CUVA conservation covenant does protect land and natural resources from development; primary motivation is economic (tax relief), not environmental; very weak positive
      stimulation: -0.2,  // Expands an existing 35-year-old program by adjusting a numerical cap; preserves status quo of rural land use against change; consensus maintenance measure
    },
    outcomes: {
      yes: 'Raises the maximum acreage cap for bona fide conservation use property from 2,000 to 4,000 acres per owner. Takes effect January 1, 2027. Companion legislation HB 90 is also activated.',
      no: 'Current 2,000-acre cap remains unchanged. The CUVA program continues as it has since 1990.',
    },
    explanation:
      'A constitutional amendment referred by the Georgia legislature (HR 32, passed 168-5 House and 50-1 Senate in 2025). The Conservation Use Value Assessment (CUVA) program lets agricultural, timber, and conservation-use landowners enter 10-year covenants to keep land in that use in exchange for property tax assessment at conservation-use value rather than fair-market value — a reduction of 50%+ for many parcels. The 2,000-acre cap has been unchanged since CUVA\'s creation in 1990; modern agricultural economics have increased average farm size, creating the practical rationale for expansion. The ballot language frames this as protecting "family farmland," but the legal mechanism does not restrict benefits to family farms — large timber companies, agribusiness corporations, and wealthy investors with qualifying acreage are also eligible. No official fiscal note has been published; the measure will reduce local property tax revenue by an unknown amount, with the burden shifting to other taxpayers in rural counties. No organized opposition exists as of February 2026.',
    supporters: [
      'Georgia Farm Bureau',
      'Georgia Forestry Association',
      'Rep. Chuck Efstration (R-104, bill sponsor)',
      'Sen. Blake Tillery (R, Senate sponsor)',
    ],
    opponents: [],
  },

];
