// ============================================================
// BALLOT BUILDER — CANDIDATE DATA
// Auto-generated by output-writer agent
// Generated: 2026-02-26T00:00:00.000Z
// Source: Georgia 2026 — Primary: 2026-05-19, General: 2026-11-03
//
// Contests:
//   GA-06-US-HOUSE-2026  — U.S. House GA-06 (Solid D, D+25)
//   GA-US-SENATE-2026    — U.S. Senate Georgia (Toss-up, Cook)
//   GA-GOVERNOR-2026     — Governor Georgia (Toss-up, Cook)
//
// Skipped (low-evidence, no scored files per pipeline instructions):
//   chris-capparell-ga06 (GA-06 Democratic primary, minimal public presence)
//   kia-legette          (GA Senate Democratic primary, minimal public presence)
//   reagan-box           (GA Senate Republican, horse trainer, negligible polling)
//   vinson-watkins       (GA Senate Republican, minimal news coverage)
//   elbert-bartell       (GA Senate Independent, minimal public presence)
//   develle-jackson      (GA Senate Independent, minimal public presence)
//   gregg-kirkpatrick    (GA Governor Republican, minimal public presence)
//   leland-olinger-ii    (GA Governor Republican, minimal public presence)
//   kenneth-yasger       (GA Governor Republican, minimal public presence)
//   chase-oliver         (GA Governor Libertarian, pending ballot access)
// ============================================================

import type { Candidate } from '../../src/server/types/index';

export const candidates: Candidate[] = [

  // ── GA-06-US-HOUSE-2026 — U.S. House, Georgia 6th Congressional District ───
  // Primary: 2026-05-19 | Runoff: 2026-06-16 | General: 2026-11-03
  // Race rating: Solid Democratic (Cook PVI D+25)
  // Incumbent: Lucy McBath (D) — not yet formally filed for 2026 as of 2026-02-25
  {
    id: 'lucy-mcbath',
    contestId: 'GA-06-US-HOUSE-2026',
    name: {
      full: 'Lucy McBath',
      ballotDisplay: 'Lucy McBath',
    },
    party: 'Democratic',
    incumbencyStatus: 'incumbent',
    ballotOrder: 1,
    profileSummary: 'Four-term Democratic incumbent and former Everytown for Gun Safety spokesperson whose son\'s murder catalyzed her political career; a New Democrat Coalition member who combines near-perfect environmental, labor, and civil liberties voting records with pragmatic centrist positioning on immigration and healthcare delivery.',
    positions: [
      'Signature issue: gun violence prevention — universal background checks, assault weapons ban, federal red flag laws (ERPO Act), high-capacity magazine ban',
      'Supports ACA expansion and public option, not Medicare for All; led $35/month insulin cost cap legislation',
      'LCV 96% lifetime, AFL-CIO 99%, ACLU 100% — strong progressive voting record across environment, labor, and civil liberties',
      'Co-sponsored George Floyd Justice in Policing Act; Ranking Member on House Judiciary Crime Subcommittee',
      'Voted YES on Laken Riley Act (2025) — one of 48 Democrats to back Republican immigration enforcement bill, a notable centrist deviation',
    ],
    axisStances: {
      econ_safetynet: 2,              // HIGH — AFL-CIO 99%, Heritage Action 0-2%, IRA/ACA subsidy votes
      econ_investment: 2,             // HIGH — IRA + IIJA votes, New Democrat Affordability Agenda
      econ_school_choice: 3,          // LOW — public ed funding emphasis, Education Committee; no direct anti-voucher vote found
      health_coverage_model: 3,       // HIGH — explicit ACA expansion + public option since 2018; not Medicare for All
      health_cost_control: 1,         // HIGH — led insulin cost cap law, Medicare drug negotiation vote, extends cap to private insurance 2025
      housing_supply_zoning: 3,       // MEDIUM — Feb 2026 Affordability Agenda: "cut red tape and update permitting and zoning"
      housing_affordability_tools: 4, // MEDIUM — Affordability Agenda: supply + targeted LIHTC subsidies (blended approach)
      housing_transport_priority: 3,  // LOW — voted for IIJA including transit funding; no specific transit-vs-roads position
      justice_policing_accountability: 2, // HIGH — co-sponsored George Floyd Act (qualified immunity, misconduct registry, chokehold ban); ACLU 100%
      justice_sentencing_goals: 3,    // LOW — Federal Prison Oversight Act (enacted); ACLU 100%; Laken Riley Act vote suggests centrist limits
      justice_firearms: 0,            // HIGH — most prominent gun safety advocate in Congress; Brady A, Giffords A, NRA F; supports every major category of regulation
      climate_ambition: 2,            // HIGH — LCV 94% (2024), 96% lifetime; IRA vote; "conclusive and indisputable" climate science
      climate_energy_portfolio: 2,    // MEDIUM — IRA clean energy tax credits vote; LCV near-perfect; no fossil fuel support
      climate_permitting: 5,          // LOW — housing permitting (faster) vs. environmental review (maintain) creates genuine ambiguity
    },
    valueStances: {
      universalism: 0.6,    // LCV 96%, LGBTQ equality, ACLU 100%; Laken Riley Act vote limits ceiling
      benevolence: 0.8,     // Son's murder → Congress; insulin caps, ACA subsidies, prison reform, CDC funding
      tradition: -0.3,      // Challenges gun culture, traditional gender norms, longstanding incarceration norms
      conformity: 0.5,      // 98.2% attendance, 8 bills enacted, New Democrat Coalition; institutional operator
      security: 0.5,        // Gun safety as public safety; ACA stability; Laken Riley Act vote
      power: -0.2,          // Opposes Citizens United; accepts substantial PAC support (Everytown $9M+)
      achievement: 0.3,     // Workforce dev, vocational schools, Education Committee work
      hedonism: 0.0,
      stimulation: -0.1,    // Incremental improvement through institutional channels; New Democrat Coalition
      self_direction: 0.4,  // Pro-choice, LGBTQ rights, ACLU 100%; gun regulation is counterweight
    },
  },

  {
    id: 'sonya-halpern',
    contestId: 'GA-06-US-HOUSE-2026',
    name: {
      full: 'Sonya Halpern',
      ballotDisplay: 'Sonya Halpern',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 2,
    profileSummary: 'Georgia State Senator (District 39) and former marketing executive running for the open GA-06 seat; five stated priorities are healthcare, education, economic equality, criminal justice reform, and voting rights. Pragmatic establishment Democrat who broke with her caucus on a transgender care vote while simultaneously sponsoring comprehensive civil rights legislation.',
    positions: [
      'Primary sponsor of SB 320 (Georgia Civil Rights Act of 2025) covering race, sex, sexual orientation, gender identity, disability, and national origin',
      'Consistent Medicaid expansion advocate; strongly opposes Georgia\'s abortion ban, framing it as healthcare access',
      'Advocates universal background checks and safe storage laws; NRA rating of 7%',
      'Platform includes ending cash bail, banning no-knock warrants, and eliminating mandatory minimums',
      'Sponsored HBCU innovation districts bill (SB 235, passed 46-7) and Georgia Music Office Act',
    ],
    axisStances: {
      econ_safetynet: 2,              // MEDIUM — Medicaid expansion advocacy, Social Security/Medicare defense, tariff opposition
      econ_investment: 2,             // MEDIUM — SB 235 HBCU Innovation Districts, SB 182 Music Office, workforce bills
      health_coverage_model: 2,       // MEDIUM — consistent Medicaid expansion advocacy; no Medicare-for-All framing
      health_public_health: 2,        // MEDIUM — abortion framing through public health lens; addiction recovery working group co-chair
      justice_policing_accountability: 2, // LOW — stated platform: end cash bail, ban no-knock warrants, ban excessive force; no confirmed bill votes
      justice_sentencing_goals: 2,    // LOW — stated platform: eliminate mandatory minimums, end cash bail; no confirmed votes
      justice_firearms: 2,            // MEDIUM — NRA 7%; explicit advocacy for universal background checks and safe storage
    },
    valueStances: {
      universalism: 0.5,    // SB 320 comprehensive civil rights; Medicaid advocacy; SB 185 vote (transgender inmates) limits ceiling
      benevolence: 0.7,     // YMCA board, Kennedy Center, HBCUs, drowning prevention, healthcare access; 26 years in district
      tradition: -0.1,      // SB 320 challenges GA status quo; SB 185 preserves existing practice (mixed)
      conformity: 0.5,      // Institutional channels throughout; state legislature, formal letters, caucus vice chair
      security: 0.4,        // Medicaid + Social Security defense (economic security); gun safety (community safety)
      power: 0.2,           // Democratic Caucus Vice Chair, Kennedy Center presidential appointment, EMILY's List
      achievement: 0.5,     // MBA, Disney/ESPN/Cox career, Kennedy Center chair, bipartisan legislative accomplishments
      hedonism: 0.0,
      stimulation: 0.2,     // SB 320 would create GA's first comprehensive civil rights law; incremental institutional approach
      self_direction: 0.3,  // Reproductive rights, SB 320 protections; SB 185 vote limits transgender self-direction
    },
  },

  {
    id: 'justin-pinker',
    contestId: 'GA-06-US-HOUSE-2026',
    name: {
      full: 'Justin Pinker',
      ballotDisplay: 'Justin Pinker',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 3,
    profileSummary: 'First-time Republican challenger in a D+25 district; businessman and community activist whose campaign is built entirely on "freedom" rhetoric covering border security, public safety, education content, and anti-surveillance themes, with no specific policy commitments on any issue.',
    positions: [
      'Supports border security ("Freedom is knowing our borders are secure") with no specific policy mechanism stated',
      'Emphasizes public safety and anti-drug-gang messaging as critique of incumbent',
      'Opposes "deviant subjects" in schools, aligning with parental rights / curriculum restriction movement',
      'Anti-government surveillance and free speech emphasis ("your keystrokes can land you on a government watchlist")',
    ],
    axisStances: {
      // Only one axis scored — all others have no stated position or are too vague
      justice_policing_accountability: 7, // LOW — public safety messaging frames crime and drug gangs as primary problem; no policy specifics
    },
    valueStances: {
      universalism: -0.2,   // Border security rhetoric; "deviant subjects" signals limits on inclusion
      benevolence: 0.2,     // Generic community welfare rhetoric (jobs, wages, homeownership, playground safety)
      tradition: 0.3,       // "Deviant subjects" language signals cultural conservatism
      conformity: 0.1,      // Public safety messaging and law-enforcement lean; anti-watchlist signal creates mild tension
      security: 0.5,        // Border security and public safety are two of five stated themes
      power: 0.0,
      achievement: 0.2,     // Prosperity-through-work framing; businessman background
      hedonism: 0.0,
      stimulation: 0.1,     // Running as first-time candidate against four-term incumbent in D+25 district
      self_direction: 0.5,  // "Fighting for Freedom" brand; anti-surveillance, free speech themes; selective (education position limits it)
    },
  },


  // ── GA-US-SENATE-2026 — U.S. Senate, Georgia ────────────────────────────────
  // Primary: 2026-05-19 | Runoff: 2026-06-16 | General: 2026-11-03
  // Race rating: Toss-up (Cook Political Report)
  // Incumbent: Jon Ossoff (D) — Class II seat
  // Republican primary frontrunner: Mike Collins (36% polling, Feb 2026)
  {
    id: 'jon-ossoff',
    contestId: 'GA-US-SENATE-2026',
    name: {
      full: 'T. Jonathan Ossoff',
      ballotDisplay: 'Jon Ossoff',
    },
    party: 'Democratic',
    incumbencyStatus: 'incumbent',
    ballotOrder: 1,
    profileSummary: 'First-term Democratic senator with a center-left voting record (97% Biden alignment), strong climate and healthcare credentials, and a distinctive anti-corruption/oversight identity built through PSI investigations. Positions as a bipartisan dealmaker on select issues while sharply opposing Trump on democratic norms.',
    positions: [
      'Supports ACA expansion and a public option, explicitly opposes Medicare for All',
      'LCV 97% lifetime; voted for IRA (largest US climate bill); sponsored Solar Manufacturing Act',
      'Voted for Bipartisan Safer Communities Act; supports universal background checks and red flag laws',
      'Primary sponsor of Federal Prison Oversight Act (signed into law 2024) — bipartisan prison conditions reform',
      'Complex immigration stance: voted YES on Laken Riley Act (enforcement) while leading investigations into ICE detention abuse',
    ],
    axisStances: {
      econ_safetynet: 2,              // HIGH — American Rescue Plan, IRA ACA subsidy extension, Heritage Action 6%, rural clinic defense
      econ_investment: 1,             // HIGH — ARP + BIL + IRA + CHIPS all voted YES; Solar Manufacturing Act enacted; debt-free college platform
      health_coverage_model: 3,       // HIGH — explicit public option support since 2020; explicitly opposes Medicare for All; ACA subsidy focus 2026
      health_cost_control: 2,         // HIGH — IRA Medicare drug negotiation vote, $35 insulin cap for seniors, drug import support
      health_public_health: 3,        // LOW — ARP public health funding, CDC full funding statement; no specific mandate positions
      justice_policing_accountability: 3, // LOW — Federal Prison Oversight Act, ICE accountability investigations, DHS funding conditioned on civil liberties; no direct policing votes
      justice_sentencing_goals: 3,    // LOW — Federal Prison Oversight Act (humane treatment orientation); no specific sentencing votes
      justice_firearms: 3,            // HIGH — Bipartisan Safer Communities Act vote (2022); supports universal background checks and red flag laws
      climate_ambition: 2,            // HIGH — LCV 97% lifetime, IRA vote (~$369B), Solar Manufacturing Act; investment/jobs framing (not emergency-phase-out)
      climate_energy_portfolio: 2,    // HIGH — Solar Manufacturing Act, Clean Energy for All Homes Act, Zero-Emission Homes Act; no fossil fuel support
    },
    valueStances: {
      universalism: 0.6,    // LCV 97%, healthcare advocacy, voting rights; Laken Riley Act vote and Israel arms position limit ceiling
      benevolence: 0.7,     // ACA subsidies for 1.4M Georgians, rural hospital defense, manufacturing jobs, prison reform, CDC funding
      tradition: -0.2,      // Progressive tax reform, voting rights expansion, clean energy transition, prison reform; invokes civil rights tradition
      conformity: 0.6,      // Bipartisan legislating signature; ranked #33 Senate bipartisanship index; PSI investigations through process
      security: 0.4,        // ACA subsidies, BIL infrastructure, CDC funding; Laken Riley Act; balances security against civil liberties
      power: -0.3,          // End Citizens United A+, Congressional stock trading ban; establishment-backed ($25M CoH) moderates score
      achievement: 0.3,     // Workforce dev through debt-free college, CHIPS Act, Solar Manufacturing Act; small business tax legislation
      hedonism: 0.0,
      stimulation: 0.2,     // Structural reform proposals through conventional legislative channels; youngest Dem senator since Biden
      self_direction: 0.4,  // Pro-choice, voting rights, ICE detention reform; gun regulation and ARP collective framing as counterweights
    },
  },

  {
    id: 'buddy-carter',
    contestId: 'GA-US-SENATE-2026',
    name: {
      full: 'Earl LeRoy "Buddy" Carter',
      ballotDisplay: 'Buddy Carter',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 2,
    profileSummary: 'Six-term Georgia congressman, pharmacist, and self-described "MAGA warrior" running for Senate on border security and Trump alignment. Chairs House Energy & Commerce Health Subcommittee; led nearly $1 trillion in Medicaid cuts in the One Big Beautiful Bill and introduced the FairTax Act to abolish the IRS.',
    positions: [
      'Led $880B+ Medicaid cuts as Health Subcommittee Chair; said he\'d "like to see more"',
      'Introduced FairTax Act (H.R. 25) to replace income tax with 23% national sales tax and abolish IRS',
      'NRA A-rated; voted against Bipartisan Safer Communities Act and universal background checks',
      'LCV 3% (2024), 4% lifetime; voted against Inflation Reduction Act climate provisions',
      'Champions PBM reform and drug pricing transparency through market competition, not government negotiation',
    ],
    axisStances: {
      econ_safetynet: 9,              // HIGH — led $880B+ Medicaid cuts; "I'd like to see more"; SNAP work requirements; refused shutdown restore
      econ_investment: 9,             // HIGH — FairTax Act (abolish IRS); TCJA "proudest vote"; voted against IRA; Heritage Action rising to 92%
      econ_school_choice: 8,          // MEDIUM — cosponsored School Choice Week resolution; eliminates Common Core; pro-voucher direction
      health_coverage_model: 9,       // HIGH — 9 ACA repeal votes; led Medicaid cuts as Health Subcommittee Chair; "market-driven solutions"
      health_cost_control: 8,         // HIGH — PBM Reform Act (market transparency over price controls); opposed Medicare drug negotiation in IRA
      health_public_health: 8,        // MEDIUM — opposed ACA individual mandate (multiple votes); Heritage Action 92% liberty framing; inference from pattern
      justice_policing_accountability: 9, // HIGH — resolution condemning anti-ICE protests; defended ICE after citizen shooting; called for expanded ICE in Atlanta
      justice_sentencing_goals: 7,    // MEDIUM — opposed DC mandatory minimum elimination; voted against MORE Act (expungement); bipartisan reform rhetoric not matched by votes
      justice_firearms: 9,            // HIGH — NRA A-grade every cycle since 2014; voted NO on Bipartisan Safer Communities Act; voted NO on H.R.8; supports national right-to-carry
      climate_ambition: 9,            // HIGH — LCV 3% (2024), 4% lifetime; voted against IRA climate provisions; supports offshore drilling
      climate_energy_portfolio: 8,    // HIGH — "all-of-the-above energy approach, which begins with increasing domestic production"; voted against IRA; IRA exception for Hyundai district investment prevents 9+
      climate_permitting: 8,          // MEDIUM — "cut bureaucratic red tape on American-made fuel and energy"; Heritage Action 92% deregulatory; no specific permitting votes found
    },
    valueStances: {
      universalism: -0.6,   // LCV 4% lifetime, voted against Respect for Marriage Act, anti-immigrant enforcement, voted to decertify PA results
      benevolence: 0.1,     // PBM reform for pharmacy communities; led $880B+ Medicaid cuts (CBO: 10.5M lose coverage) counteracts
      tradition: 0.7,       // A+ SBA Pro-Life, voted against same-sex marriage, transgender athlete ban campaign priority, religious/cultural conservatism
      conformity: -0.2,     // Voted to decertify PA electoral votes; "MAGA warrior" identity; IRA pragmatism exception shows some institutional playing
      security: 0.7,        // Border security top priority; "peace through strength"; strong law enforcement; Medicaid cuts reduce economic security
      power: 0.5,           // Chamber of Commerce alignment, TCJA support, FairTax shifts burden to consumers; some PBM challenge of pharma
      achievement: 0.6,     // "Lifeline, not a lifestyle" framing; work requirements; self-made pharmacist identity; school choice
      hedonism: -0.3,       // Voted against MORE Act; transgender/same-sex restrictions; social conservatism
      stimulation: 0.1,     // FairTax is genuinely radical (abolish IRS); overall pattern is status-quo-defending
      self_direction: 0.2,  // Gun rights (NRA A-grade), school choice, FairTax economic freedom; opposes reproductive choice, same-sex marriage protections
    },
  },

  {
    id: 'mike-collins',
    contestId: 'GA-US-SENATE-2026',
    name: {
      full: 'Michael Collins',
      ballotDisplay: 'Mike Collins',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 3,
    profileSummary: 'Two-term hard-right congressman and trucking company owner running on a MAGA/America First platform; Heritage Action 98%, LCV 1%, sponsor of the Laken Riley Act, and one of the most conservative members of the House delegation.',
    positions: [
      'Sponsored the Laken Riley Act (signed into law Jan 2025) and supports immigration moratorium including reduced legal immigration',
      'Advocates abolishing the ATF, repealing the NFA, and national constitutional carry (GGO 100%, NRA ~92%)',
      'LCV 1% lifetime; calls green energy policies "ridiculous" and champions "drill here, drill now"',
      'Voted for One Big Beautiful Bill ($800B Medicaid cuts); told retirees to "get off Social Security, get back in the workforce"',
      'Cosponsored personhood bill recognizing life at conception; opposes all Planned Parenthood funding',
    ],
    axisStances: {
      econ_safetynet: 9,              // HIGH — "get off Social Security, get back in the workforce" (radio, June 2025); OBBBA $800B Medicaid cuts vote; Heritage Action 98%
      econ_investment: 9,             // HIGH — Heritage Action 98%; balanced budget pledge; voted against Fiscal Responsibility Act as too moderate; Chamber "leader on tax reform"
      econ_school_choice: 8,          // MEDIUM — Heritage Action 98% (Heritage heavily weights school choice); no direct votes or statements found; inferred
      health_coverage_model: 9,       // HIGH — OBBBA vote ($800B Medicaid cuts, CBO: 11.8M lose coverage); iVoterGuide: "between C and D" on taxpayer-funded healthcare; "get off Medicaid"
      health_cost_control: 8,         // LOW — Heritage Action 98% (Heritage opposes drug price controls); no specific positions found; fully inferred
      health_public_health: 7,        // MEDIUM — TRANQ Act (bipartisan fentanyl law) shows some public health engagement; Heritage alignment suggests anti-mandate
      justice_policing_accountability: 8, // LOW — Laken Riley Act (pro-enforcement); strong law-and-order orientation; no direct policing positions
      justice_firearms: 10,           // HIGH — GGO 100%; NRA ~92%; cosponsor bill to abolish ATF and repeal NFA; "problem is not the gun" after Apalachee High School shooting
      climate_ambition: 10,           // HIGH — LCV 1% lifetime; "stop pushing these ridiculous Green Energy policies"; "Drill here, drill now"; chaired Water Resources subcommittee anti-regulatorily
      climate_energy_portfolio: 10,   // HIGH — "Drill here, drill now"; "stop pushing these ridiculous Green Energy policies"; LCV 1%; Energy and Mineral Resources subcommittee
      climate_permitting: 8,          // MEDIUM — chaired Water Resources and Environment Subcommittee in anti-regulatory direction; Heritage Action 98%
    },
    valueStances: {
      universalism: -0.7,   // LCV 1%, opposed Ukraine aid (isolationist), immigration moratorium, antisemitism-adjacent incident, AI deepfake campaign video
      benevolence: 0.0,     // TRANQ Act shows community concern; voted for OBBBA stripping up to 750K GA-10 constituents; "get off Medicaid"
      tradition: 0.7,       // "Unapologetically pro God"; personhood bill; son of former congressman; opposes Planned Parenthood; MAGA movement is itself disruptive of some traditions
      conformity: -0.3,     // AI deepfake campaign video; antisemitic social media engagement; House Ethics investigation; voted against bipartisan debt ceiling deal
      security: 0.5,        // Strong border security/Laken Riley Act/finish the wall; "get off Social Security" undermines economic security
      power: 0.5,           // Chamber of Commerce praise, Heritage alignment, built trucking company from 1 to 115 trucks; accepts donor/PAC structure
      achievement: 0.7,     // Built trucking company from one semi to 115 trucks and 100+ employees; "get back in the workforce" moral imperative
      hedonism: -0.2,       // "Pro God" social conservatism; personhood bill; opposition to Planned Parenthood
      stimulation: 0.1,     // Defied party leadership on Fiscal Responsibility Act; AI tactics; restorationist policy vision
      self_direction: 0.2,  // Abolish ATF/repeal NFA/constitutional carry; personhood bill restricts reproductive autonomy; immigration moratorium; net slightly positive on gun/economic liberty
    },
  },

  {
    id: 'derek-dooley',
    contestId: 'GA-US-SENATE-2026',
    name: {
      full: 'Derek Dooley',
      ballotDisplay: 'Derek Dooley',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 4,
    profileSummary: 'First-time candidate and former college football coach with no legislative record; running as a Kemp-backed outsider on a thin platform of lower taxes, less spending, border security, and market-based solutions.',
    positions: [
      'Lower taxes and reduced government spending — "hardworking people should keep more of their money"',
      'Border security: "opening our border makes us less safe"',
      'Market-oriented housing policy: cut government regulation to reduce home prices',
      'Rural healthcare via doctor incentives, not Medicaid expansion',
      'Pledges to support Trump\'s agenda in the Senate while maintaining Kemp-establishment positioning',
    ],
    axisStances: {
      // Only 5 axes scored — first-time candidate with no legislative record
      econ_safetynet: 7,              // LOW — general "government should spend less" messaging; DSCC Medicaid claim unverified in primary sources
      econ_investment: 7,             // LOW — deregulation and reduced-spending messaging; market-led housing/healthcare; NCAA governance exception
      health_coverage_model: 7,       // LOW — rural healthcare via doctor incentives, not program expansion; "patients and doctors" framing; no Medicaid/ACA positions
      housing_affordability_tools: 8, // LOW — would cut government regulation to reduce home prices; blamed immigration for housing shortage; no subsidy proposals found
    },
    valueStances: {
      universalism: -0.3,   // Anti-immigration framing as threat; no climate/environmental positions; transgender sports opposition
      benevolence: 0.3,     // Rural healthcare concern is personal (wife is rural OB/GYN); general community welfare messaging
      tradition: 0.5,       // Traditional gender norms (transgender sports); Georgia sports tradition (father Vince Dooley); federalist abortion framing
      conformity: 0.2,      // Defers to federalist structure; acknowledged Trump lost GA 2020 privately (publicly hedged)
      security: 0.6,        // "Opening our border makes us less safe" is prominent explicit position; "lawlessness" opposition
      power: 0.2,           // Backed by Kemp political machine; raised $2.1M+; frames as outsider
      achievement: 0.5,     // Entire biography around competitive achievement; football coaching career; law degree; "outsider who can win" framing
      hedonism: 0.0,
      stimulation: 0.1,     // New leadership rhetoric; personnel replacement rather than structural reform
      self_direction: 0.1,  // Federalist framing on abortion; lower taxes liberty dimension; transgender sports opposition
    },
  },


  // ── GA-GOVERNOR-2026 — Governor, Georgia ────────────────────────────────────
  // Primary: 2026-05-19 | Runoff: 2026-06-16 | General: 2026-11-03
  // Race rating: Toss-up (Cook Political Report); Lean R (Sabato's Crystal Ball)
  // Open seat — Brian Kemp is term-limited
  {
    id: 'keisha-lance-bottoms',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Keisha Lance Bottoms',
      ballotDisplay: 'Keisha Lance Bottoms',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 1,
    profileSummary: 'Former two-term Atlanta mayor and Biden White House advisor with a deep executive record on policing reform, climate action, affordable housing, and criminal justice reform; running on Medicaid expansion, reproductive rights, and anti-Trump framing as the Democratic frontrunner for Georgia governor.',
    positions: [
      'Full Medicaid expansion as top stated priority — 300,000 uninsured Georgians and rural hospital closures',
      'Explicit pro-Roe; opposes Georgia\'s 6-week abortion ban; EMILY\'s List endorsed',
      '100% clean energy plan for Atlanta (2025 municipal, 2035 community-wide); Senate climate testimony',
      'Closed Atlanta city jail; eliminated cash bail; signed ICE detainee ban — strong criminal justice reform record',
      'Affordable housing: $50M bond, 20,000-home goal, inclusionary zoning, corporate landlord crackdown',
    ],
    axisStances: {
      econ_safetynet: 2,              // MEDIUM — One Atlanta Economic Mobility Plan, Medicaid expansion priority, first-time homebuyer grants, teacher tax elimination
      econ_investment: 1,             // HIGH — $50M housing bond, More MARTA (largest transit investment in 40+ years), Clean Energy Atlanta Plan, balanced budgets with $181M reserves
      econ_school_choice: 3,          // LOW — teacher income tax elimination, education funding increase; no voucher/charter position
      health_coverage_model: 2,       // HIGH — "fight to expand Medicaid so 300,000 Georgians can get coverage"; repeated across all interview sources; not single-payer
      health_public_health: 2,        // MEDIUM — COVID pandemic leadership, climate-as-public-health framing, HIV funding, LGBTQ Affairs office
      housing_supply_zoning: 2,       // HIGH — ADU legalization, parking minimum elimination, inclusionary zoning, missing middle housing — actual executive actions
      housing_affordability_tools: 1, // HIGH — $50M bond, 20,000-home goal, inclusionary zoning mandates, public land for affordable housing, corporate landlord crackdown
      housing_transport_priority: 1,  // MEDIUM — More MARTA Atlanta program approval (largest regional transit investment in 40+ years); parking minimum elimination
      justice_policing_accountability: 3, // HIGH — Rayshard Brooks response (fired officer, de-escalation mandates); cash bail elimination; jail closure; simultaneously funded APD +$13M and gave historic pay raises
      justice_sentencing_goals: 2,    // MEDIUM — cash bail elimination (city ordinance), Atlanta City Detention Center closure, ICE detainee ban; all municipal-level actions
      justice_firearms: 2,            // HIGH — bipartisan 214-mayor universal background checks letter; Everytown/Moms Demand alignment; called for stricter GA laws; personal loss (nephew killed)
      climate_ambition: 1,            // HIGH — 100% clean energy municipal by 2025, community-wide by 2035; only Southern mayor to testify before Senate climate committee; joined Paris Agreement
      climate_energy_portfolio: 2,    // MEDIUM — 100% clean energy target implies renewables priority; no state-level energy portfolio position yet
      climate_permitting: 5,          // LOW — housing permitting (faster: ADU, parking) vs. environmental review (thorough: LCV near-perfect) creates genuine ambiguity
    },
    valueStances: {
      universalism: 0.7,    // Climate action, LGBTQ rights (perfect HRC scores), ICE detainee ban, cash bail elimination, equity framing; domestically focused
      benevolence: 0.8,     // Medicaid expansion, affordable housing, teacher support, small business, economic mobility plan, HIV funding — central to identity
      tradition: -0.3,      // Cash bail elimination, jail closure, police reform, ADU legalization, abortion rights; works within institutional channels
      conformity: 0.3,      // Executive orders, balanced budgets, MARTA partnerships, council legislation; ICE ban pushed federal-city limits
      security: 0.4,        // Medicaid (health security), housing (housing security), $181M reserves (fiscal security), APD pay raises; crime surge during tenure limits score
      power: -0.2,          // Corporate landlord crackdown, inclusionary zoning, ICE opposition; EMILY's List and Biden White House establishment positioning
      achievement: 0.4,     // One Atlanta Economic Mobility Plan, workforce development, career pathways; structural solutions framing over individual bootstraps
      hedonism: 0.1,        // LGBTQ rights, reproductive rights implicitly support personal autonomy; framed as justice not lifestyle liberty
      stimulation: 0.3,     // Reimagined jail as "Center for Equity," 100% clean energy plan, first LGBTQ Affairs director; institutionalist candidate
      self_direction: 0.4,  // Reproductive rights, LGBTQ rights, ICE detainee ban; housing/market intervention works against economic self-direction
    },
  },

  {
    id: 'geoff-duncan',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Geoff Duncan',
      ballotDisplay: 'Geoff Duncan',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 2,
    profileSummary: 'Former Republican Lt. Governor of Georgia (2019-2023) who switched to the Democratic Party in August 2025 after breaking with Trump over election fraud claims. Running on affordability (childcare, healthcare, housing), full Medicaid expansion, and explicit recantations of prior positions on abortion, guns, and Medicaid.',
    positions: [
      'Full Medicaid expansion funded by $1.7B "jumpstart fund" from Georgia\'s rainy day reserves',
      'Day-one executive order protecting doctors treating pregnant women; legislation to repeal Georgia\'s six-week abortion ban',
      'Universal background checks, red flag laws, and safe storage requirements — explicit reversal of prior NRA A-rating',
      'Championed Georgia\'s Hate Crimes Law (2020) and repeal of citizen\'s arrest law as Republican Lt. Governor',
      'LESS Crime Act (2022): tax credit-funded police salary increases and mental health co-responder teams',
    ],
    axisStances: {
      econ_safetynet: 3,              // MEDIUM — $1.7B jumpstart fund, CAPS and TANF expansion statements, childcare subsidies; not universal-program territory
      econ_investment: 4,             // MEDIUM — $1.7B public investment from reserves; as LG presided over GA's largest income tax cut (2022); no new tax increase proposed
      econ_school_choice: 6,          // LOW — as LG, wrote op-ed calling for expanded school choice (2019); no 2026 recantation found; scored on only available evidence
      health_coverage_model: 3,       // HIGH — explicit full Medicaid expansion with $1.7B mechanism, repeated 5+ times across independent outlets; not single-payer
      health_public_health: 4,        // LOW — Georgia Behavioral Health and Peace Officer Co-Responder Act (SB 403, 2022); no broader public health mandate positions
      housing_affordability_tools: 4, // LOW — housing affordability is a campaign pillar; jumpstart fund partially targets housing; no specific mechanism detail
      justice_policing_accountability: 5, // MEDIUM — LESS Crime Act (pro-police funding: tax credits for salary increases); Co-Responder Act (mental health teams alongside police); genuine centrist
      justice_firearms: 3,            // MEDIUM — 2018 NRA A-rated, NRA-endorsed; 2026: calls NRA "fear mongering," supports universal background checks, red flag laws, safe storage; explicit recantation across 3+ outlets
    },
    valueStances: {
      universalism: 0.4,    // Hate Crimes Law, citizen's arrest repeal, "love thy neighbor" framing, Medicaid expansion; Georgia-focused, no international signals
      benevolence: 0.7,     // "Love thy neighbor" central to party switch; three pillars (childcare, healthcare, housing) are direct community welfare; Rural Hospital Tax Credit
      tradition: -0.3,      // Switching parties and recanting multiple long-held positions; repealing citizen's arrest law; uses faith tradition to justify departure from political tradition
      conformity: 0.5,      // Refused to overturn 2020 election under intense pressure; built bipartisan coalitions through legislative process; party switch through legitimate channels
      security: 0.4,        // LESS Crime Act (police salary funding), Co-Responder Act, Medicaid expansion as health security; no border/national defense positions
      power: 0.1,           // Former constitutional officer; founded and sold business; defied GOP, NRA, Trump; no major PAC endorsements
      achievement: 0.4,     // Former AAA minor league pitcher; founded and sold marketing company; Georgia Tech scholarship; "GOP 2.0" authorship
      hedonism: 0.0,
      stimulation: 0.4,     // Party switch is the most dramatic norm-breaking act in 2026 GA cycle; pragmatic moderate policy proposals
      self_direction: 0.3,  // 2020 defiance was independent thinking; reproductive rights framing; prior record (Heartbeat Bill, NRA) moderates current-cycle signals
    },
  },

  {
    id: 'jason-esteves',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Jason Esteves',
      ballotDisplay: 'Jason Esteves',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 3,
    profileSummary: 'Former Georgia State Senator (District 35, 2023-2025) and eight-year Atlanta Public Schools Board member who resigned to run for governor. Corporate attorney turned progressive campaigner centering education, Medicaid expansion, reproductive rights, and anti-corporate housing policy.',
    positions: [
      'Full Medicaid expansion for Georgia; lower prescription drug costs; expand rural hospitals and senior care',
      'Repeal Georgia\'s six-week abortion ban (sponsored heartbeat bill repeal as state senator)',
      'Fully fund public schools and oppose education vouchers; universal childcare for 3- and 4-year-olds funded by Georgia Lottery reserves',
      'Ban private equity firms from purchasing single-family homes; strengthen renter protections; increase housing supply',
      '$1 billion low-interest loan fund for small businesses; opposes Kemp\'s mega-corporation incentive model',
    ],
    axisStances: {
      econ_safetynet: 2,              // MEDIUM — $1B small business fund, universal childcare via lottery reserves, National Guard for food banks if federal programs cut
      econ_investment: 2,             // MEDIUM — $1B small business fund, universal childcare via lottery reserves, education funding increase; criticizes Kemp mega-corporation focus
      econ_school_choice: 1,          // HIGH — "stood up against voucher schemes that siphon resources away from our public schools"; 8 years APS Board; sponsored early learning expansion
      health_coverage_model: 3,       // HIGH — Medicaid expansion across multiple forums; SB 199 HSA bill shows comfort with market tools within public framework
      health_cost_control: 4,         // LOW — "lower the cost of prescription drugs" on platform; SB 199 (market mechanism for employee benefits); no specific mechanism documented
      health_public_health: 3,        // MEDIUM — heartbeat bill repeal (Tier 1 legislative), maternal mortality framing, free-range parenting bill co-sponsor (individual liberty signal)
      housing_affordability_tools: 2, // HIGH — PE home purchase restriction bill (Tier 1 legislative), renter protections, "stop private equity from buying single-family homes"
      housing_supply_zoning: 4,       // LOW — "increase the housing supply" (general); defeated Buckhead cityhood bill (indirect density signal); no specific zoning positions
      housing_transport_priority: 4,  // LOW — "expanding public transportation" (single general mention); no specifics
      justice_firearms: 3,            // MEDIUM — opposed permitless carry (2022 Senate campaign); criticized Duncan for "preventing sensible gun ownership laws"
      justice_sentencing_goals: 4,    // LOW — SB 25 Parole Board Transparency (mild due-process signal); single narrow bill
      climate_ambition: 4,            // LOW — "advocate for renewable energy sources"; 2021 op-ed on zero-emission school buses; no specific emissions targets or climate legislation
    },
    valueStances: {
      universalism: 0.5,    // Medicaid expansion, universal childcare, maternal mortality equity framing ("especially for black women"), housing protections; domestic in scope
      benevolence: 0.7,     // 8 years unpaid school board service including as Chair; Teach For America; teacher pay, rural hospital expansion, senior property tax relief, small business fund
      tradition: -0.1,      // Repeal of abortion ban challenges recent law; defends public school system and unified city governance; mildly change-oriented
      conformity: 0.4,      // Bipartisan legislative record (SB 199, senior tax relief, free-range parenting all passed with Republican support); resigned Senate seat properly to run
      security: 0.4,        // National Guard for food banks, rural hospital expansion, housing as family stability, senior property tax relief, personal info redaction for officials
      power: -0.2,          // Anti-corporate housing and economic positions; claims 95% small-dollar fundraising (unverified); establishment endorsements (Carter, Yates) moderate score
      achievement: 0.5,     // First-gen college grad, son of immigrants, Emory Law, VP at Equifax, three family businesses, APS Board Chair, State Senator
      hedonism: 0.1,        // Free-range parenting bill (personal liberty); reproductive rights framed as healthcare decisions
      stimulation: 0.2,     // Resigned safe seat to run; PE home purchase ban; lottery-reserve-funded childcare; standard progressive framework
      self_direction: 0.4,  // "Woman's right to make her own healthcare decisions"; free-range parenting bill; anti-voucher limits education self-direction
    },
  },

  {
    id: 'michael-thurmond',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Michael Thurmond',
      ballotDisplay: 'Michael Thurmond',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 4,
    profileSummary: 'Veteran Georgia Democrat with nearly four decades of executive governance experience — Labor Commissioner, DeKalb County CEO, interim school superintendent — running on fiscal pragmatism, Medicaid expansion, public school investment, and bipartisan bridge-building. Deliberately avoids climate, guns, criminal justice, and social issues in his campaign framing.',
    positions: [
      'Full Medicaid expansion in first year; frames healthcare as a right with focus on maternal mortality and rural access',
      'Fully fund public schools, modernize QBE funding formula, raise teacher pay, expand pre-K for 3- and 4-year-olds',
      'AI workforce initiative through technical colleges and two-year institutions to create "most AI proficient workforce in America"',
      'Opposes income tax elimination; cites regressivity of sales tax replacement on low-income Georgians',
      'Day-one executive order declaring housing affordability a statewide crisis; partnership model with local governments and private developers',
    ],
    axisStances: {
      econ_safetynet: 2,              // HIGH — Labor Commissioner record: raised unemployment benefits; DeKalb CEO COVID rental assistance/food programs; $250M senior/worker tax relief as GA House member
      econ_investment: 2,             // HIGH — DeKalb water/sewer infrastructure, $150M rainy-day fund (fiscal discipline + investment), AI workforce training, community bank initiative
      econ_tax_structure: 4,          // MEDIUM — explicitly opposed income tax elimination (regressivity framing); delivered $1.2B employer tax cut as Labor Commissioner; protects existing structure, not pushing it leftward
      econ_school_choice: 1,          // HIGH — exclusively pro-public school; reversed DeKalb accreditation crisis as interim superintendent; zero mention of vouchers/charters across all sources
      health_coverage_model: 3,       // HIGH — "protect it and expand it" (Medicaid); "healthcare is a right every Georgian should have"; maternal mortality and rural hospital access framing; not single-payer
      housing_affordability_tools: 3, // MEDIUM — Day 1 executive order declaring housing affordability a statewide crisis; partnership with cities/counties/private developers; COVID rental assistance
      housing_supply_zoning: 4,       // LOW — partnership for "more affordable multi-family and single-family units" (single source); multi-family mention implies some density support
    },
    valueStances: {
      universalism: 0.3,    // Healthcare-as-right framing, housing crisis declaration, water infrastructure; "hire local labor rather than foreigners" statement is anti-universalist signal
      benevolence: 0.8,     // Defining characteristic: 35+ years raising unemployment benefits, rescuing schools, COVID food/rental assistance, retention bonuses; "fight for working families"
      tradition: 0.3,       // Author of multiple Georgia history books; deep respect for heritage; first Black statewide official since Reconstruction; AI modernization modernizes without breaking tradition
      conformity: 0.6,      // Eight consecutive balanced budgets; $150M rainy-day fund; reversed accreditation crisis meeting standards; bridge-builder framing; process-respecting governance
      security: 0.6,        // Fiscal stability ($24.7M deficit to $150M reserve), food security, healthcare access, water infrastructure, "a job for every Georgian" as economic security
      power: 0.1,           // Held significant institutional power (3-term statewide official, 2-term county CEO); no major corporate PAC alignment; $1.2B employer tax cut is pro-business but paired with worker benefits
      achievement: 0.6,     // Sharecropper's son to first Black statewide official since Reconstruction; "a job for every Georgian and a Georgian for every job"; AI workforce training and technical college expansion
      hedonism: 0.0,
      stimulation: 0.1,     // AI workforce initiative shows modest innovation interest; overall identity is pragmatic/institutional/stable
      self_direction: 0.2,  // Election board independence; healthcare-as-right enabling autonomy; no documented reproductive rights, LGBTQ, or surveillance positions
    },
  },

  {
    id: 'derrick-jackson',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Derrick Jackson',
      ballotDisplay: 'Derrick Jackson',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 5,
    profileSummary: 'Five-term Georgia state representative and 22-year Navy veteran running as a progressive anti-establishment Democrat; anchored by Medicaid expansion, aggressive minimum wage increases, comprehensive gun regulation, and repeal of Georgia\'s six-week abortion ban.',
    positions: [
      'Full Medicaid expansion to protect rural hospitals and expand access statewide',
      'Raise Georgia minimum wage to $27/hour by 2028 via phased increases (sponsored legislation)',
      'Repeal Georgia\'s six-week abortion ban (HB 481); voted NO on the bill in 2019',
      'Sponsored HB 601, described as "the biggest gun control bill in Georgia history" by gun-rights critics',
      'Eliminate state income tax for nurses, teachers, veterans, and seniors over 65',
    ],
    axisStances: {
      econ_safetynet: 2,              // HIGH — Medicaid expansion, sponsored minimum wage bill ($27/hr), budget surplus for social investment, targeted tax exemptions for workers/retirees
      econ_investment: 2,             // MEDIUM — proposes using GA's $14.8B surplus for public investment; rural broadband, telemedicine, small business grants, Black farmer capital access
      econ_tax_structure: 3,          // LOW — targeted income tax exemptions for four groups (nurses, teachers, vets, seniors 65+); progressive in direction but uses exemptions not rate changes
      econ_school_choice: 2,          // MEDIUM — consistent emphasis on strengthening public schools (QBE reform, pre-K through tech college); no private school/choice language in any source
      health_coverage_model: 2,       // HIGH — full Medicaid expansion stated at every documented forum appearance; rural hospital survival framing; not Medicare for All
      health_cost_control: 3,         // LOW — rural hospital protection, Medicaid expansion as indirect cost leverage; no specific drug pricing or rate-setting positions
      justice_policing_accountability: 3, // LOW — "reimagine community safety from an intersectional perspective"; "address school-to-prison pipeline"; anti-ICE rhetoric; no specific policy proposals
      justice_firearms: 1,            // HIGH — sponsored HB 601 (Georgia Gun Safe Act of 2025); gun-rights critics describe as "biggest gun control bill in GA history"; sponsored companion HB 711
      climate_ambition: 3,            // LOW — "invest in renewable energy and sustainable practices"; environmental equity framing (clean air, safe water, no income/race/zip disparities); no specific emissions targets
    },
    valueStances: {
      universalism: 0.5,    // Environmental justice framing, immigrant rights defense, reparations, reproductive rights; Georgia-focused, not globally expansive
      benevolence: 0.8,     // Every policy framed as community care: Medicaid, minimum wage, teacher pay, veteran support, rural broadband; father of 7, grandfather; "this is personal, every day I will come"
      tradition: -0.2,      // Seeks to repeal HB 481, $27/hr minimum wage upends GA economic model, comprehensive gun regulation in gun-friendly state; 22-year military and long legislative tenure show institutional respect
      conformity: 0.3,      // Five-term legislator; 314 bills sponsored; serves on committees; anti-establishment rhetoric and confrontational ICE language moderate score
      security: 0.4,        // 22-year Navy career; rural hospital protection; minimum wage/Medicaid as economic security; "reimagine community safety" works against traditional security framing
      power: -0.4,          // Anti-establishment positioning; no confirmed corporate PAC support; labor-centered economic policy; challenges ICE (federal enforcement power)
      achievement: 0.5,     // 42 years of experience; PhD candidate; GE career; 314 bills; emphasizes resume and experience as differentiators
      hedonism: 0.0,
      stimulation: 0.5,     // $27/hr minimum wage (would be highest state minimum in US), HB 601 as "biggest gun control bill in GA history," reparations at gubernatorial level; operates through institutional channels
      self_direction: 0.2,  // Reproductive rights framed as bodily autonomy ("daughters should have bodily autonomy just like sons"); comprehensive gun regulation (HB 601) is substantial counterweight
    },
  },

  {
    id: 'olu-brown',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Olu Brown',
      ballotDisplay: 'Olu Brown',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 6,
    profileSummary: 'Former megachurch pastor and small business consultant with no prior elected office; campaigns on healthcare access, teacher pay, small business investment, and rural equity as a progressive outsider in a crowded Democratic primary.',
    positions: [
      'Expand Medicaid and ACA in Georgia; invest in telehealth and maternal/prenatal care for rural access',
      'Direct Georgia\'s $14B+ budget surplus to small business capital reserves, healthcare, and education rather than tax cuts',
      'Raise educator pay; reform QBE formula; add technical/vocational education in high schools',
      'Push Georgia toward a living wage through business accountability',
      'Invest in affordable housing fund and rental assistance',
    ],
    axisStances: {
      econ_safetynet: 2,              // MEDIUM — Medicaid expansion, living/minimum wage, affordable housing, surplus-to-services; no voting record (first-time candidate)
      econ_investment: 2,             // MEDIUM — small business capital reserve and first-hire tax credit; consistent public investment orientation; "invest the surplus not cut taxes"
      econ_tax_structure: 3,          // LOW — consistent preference for surplus-to-services over tax cuts; targeted small business credits; no direct income/corporate tax position
      econ_school_choice: 2,          // LOW — entirely public-school-focused: teacher compensation, QBE reform, vocational tracks; no voucher/charter position found
      health_coverage_model: 3,       // MEDIUM — Medicaid expansion and ACA expansion stated across 5 sources; "universal healthcare coverage" used once (likely shorthand); scored on preponderance at Medicaid expansion tier
      housing_affordability_tools: 3, // LOW — affordable housing fund, rental assistance at NAACP forum; single forum appearance; no mechanism specifics
    },
    valueStances: {
      universalism: 0.5,    // LGBTQ+ advocacy framed as justice; regional equity across all of Georgia including rural communities; no environmental/climate positions
      benevolence: 0.8,     // Built community from 25 to 5,000+ members over 15 years; 30+ listening sessions across Georgia; healthcare, education, small business, housing all framed as community welfare
      tradition: 0.1,       // 15-year United Methodist pastor (traditional institution); challenged church orthodoxy on LGBTQ+ inclusion; "new vision for Georgia"
      conformity: 0.3,      // Led denominational institution 15 years; running through democratic process; pledged to fully fund election boards; no norm-violating behavior
      security: 0.4,        // Healthcare access ("cheaper to keep you healthy"), affordable housing and living wage as stability, "firewall against Trump's chaos"
      power: -0.2,          // No corporate PAC backing; "hold businesses accountable"; surplus to services not wealthy tax cuts; not aggressively anti-corporate
      achievement: 0.6,     // Grew church from 25 to 5,000+ with $4M budget; pivoted to consulting firm; small business capital reserves and first-hire tax credits; vocational education
      hedonism: 0.0,
      stimulation: 0.5,     // First-time candidate challenging established politicians; "new vision for Georgia"; 30+ grassroots listening sessions; pulpit-to-politics career pivot
      self_direction: 0.3,  // LGBTQ+ inclusion advocacy is notable independent stance for a Black megachurch pastor; limited evidence on civil liberties broadly
    },
  },

  {
    id: 'ruwa-romman',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Ruwa Romman',
      ballotDisplay: 'Ruwa Romman',
    },
    party: 'Democratic',
    incumbencyStatus: 'challenger',
    ballotOrder: 7,
    profileSummary: 'First-term state legislator and community organizer running on an explicitly populist, class-based economic platform. First Palestinian-American and first Muslim woman elected to the Georgia House; national profile elevated by DNC/Uncommitted episode in 2024.',
    positions: [
      'Full Medicaid expansion to reopen rural hospitals and strengthen Georgia\'s workforce',
      'Raise the minimum wage from the federal $7.25 floor, which Georgia has not touched since 1997',
      'Force corporations to divest single-family homes they purchased; anti-corporate-landlord legislation',
      'Restore reproductive rights access and veto any bill targeting LGBTQ or transgender Georgians',
      'Repeal HB 1105 (Georgia Criminal Alien Track and Report Act); opposes ICE detention-for-profit',
    ],
    axisStances: {
      econ_safetynet: 1,              // HIGH — minimum wage as central campaign commitment, "feed hungry kids," Medicaid expansion, EMS Essential Service Designation Bill
      econ_investment: 2,             // MEDIUM — small business investment and apprenticeship programs, childcare support, Medicaid expansion as workforce development, consumer protection restoration
      econ_tax_structure: 2,          // LOW — "top versus bottom" class framing throughout platform; anti-corporate populism; no specific tax proposal found; inferred from platform
      econ_school_choice: 2,          // LOW — critique of Republican education outcomes; DEI defense; general pro-public-school framing; no explicit voucher position
      health_coverage_model: 3,       // HIGH — Medicaid expansion stated across 5 independent sources; no single-payer advocacy; scored at public option/Medicaid expansion tier
      housing_affordability_tools: 2, // HIGH — sponsored legislation forcing corporate divestiture of single-family homes (Tier 1 legislative); "take homes back from corporations"; distinguished at forums for strongest housing position
      justice_policing_accountability: 3, // LOW — HB 1105 opposition (immigration enforcement, adjacent to policing); LGBTQ/trans rights veto (civil liberties); Fair Fight endorsement; no direct policing reform statements
      climate_permitting: 2,          // LOW — HB 1012 (Data Center Moratorium, primary sponsor, bipartisan): "before we permanently alter the landscape... we have an obligation to properly regulate and assess"; precautionary principle
    },
    valueStances: {
      universalism: 0.7,    // LGBTQ/trans veto, reproductive rights, immigration protection (HB 1105 repeal), DEI defense, Palestinian advocacy and DNC ceasefire speech; draws cross-group solidarity connections
      benevolence: 0.8,     // Co-founded Georgia Volunteer Hub; CAIR communications director; EMS essential service, consumer protection, corporate landlord legislation, minimum wage; "our job is to be moral leaders"
      tradition: -0.4,      // First Muslim woman in GA House; campaigns explicitly against 20+ years of Republican tradition; reproductive rights; LGBTQ rights; rejects centrist Democratic strategic tradition
      conformity: 0.2,      // Works within the system (state legislator, bipartisan bills); endorsed Harris despite DNC snub; did not call for arms embargo; populist outsider framing reduces score
      security: 0.3,        // Food security, healthcare access, EMS essential service designation; opposes immigration enforcement (HB 1105 repeal) which challenges security framing
      power: -0.7,          // "Top versus bottom" class framing is the core campaign thesis; force corporate home divestiture; ICE detention as "financially lucrative for billionaire benefactors"; consumer protection; Georgia Working Families Party endorsement
      achievement: 0.1,     // Georgetown MPP, Deloitte career; apprenticeship programs, small business empowerment; structural barriers framing subordinates achievement to systemic analysis
      hedonism: 0.1,        // Reproductive rights and LGBTQ rights framed as minority rights, not lifestyle liberty
      stimulation: 0.6,     // Historic candidacy (first Palestinian/Muslim woman); Project 159 grassroots strategy (all 159 GA counties); explicit rejection of centrist Democratic playbook; DNC speech outside venue after denied the stage
      self_direction: 0.4,  // Reproductive rights as bodily autonomy, LGBTQ rights, anti-surveillance (ICE detention opposition), DEI as self-determination; government market regulation (corporate landlord divestiture, data center moratorium) as counterweight
    },
  },

  {
    id: 'burt-jones',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Burt Jones',
      ballotDisplay: 'Burt Jones',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 8,
    profileSummary: 'Georgia Lt. Governor and Trump-endorsed gubernatorial candidate with a 10-year state Senate record; defines his platform around eliminating the state income tax, expanding school choice, and tough-on-crime mandatory minimums. Signed false elector certificates after 2020 and faces ongoing conflict-of-interest scrutiny over a family-tied data center project.',
    positions: [
      'Signature promise to completely eliminate Georgia\'s state income tax by 2032; only candidate to sign ATR Taxpayer Protection Pledge',
      'Led passage of Georgia Promise Scholarship (school vouchers) and seeks to permanently lock in federal scholarship participation',
      'Tough-on-crime agenda: mandatory minimums for gang offenses, expanded cash bail, death penalty for fentanyl dealers',
      'Explicitly opposes all new gun restrictions; proposed $10K/year stipend for teachers who carry firearms',
      'Supports Georgia\'s 6-week heartbeat abortion ban; led transgender sports ban (Riley Gaines Act)',
    ],
    axisStances: {
      econ_safetynet: 8,              // HIGH — ATR Taxpayer Protection Pledge; income tax elimination; Senate income tax cut record; framing entirely around reducing government revenue
      econ_investment: 8,             // HIGH — income tax elimination plan (reduces state revenue by billions); CON reform (market-oriented); ATR pledge constrains public investment
      econ_school_choice: 9,          // HIGH — SB 233 (Georgia Promise Scholarship, GA's first voucher program); SB 446 (permanent federal scholarship participation); "most significant school choice victory in state history"
      health_coverage_model: 7,       // MEDIUM — long Senate record opposing Medicaid expansion; CON reform (market healthcare access); recent rhetorical openness to Arkansas-style (private marketplace) expansion; voted against expansion throughout career
      health_cost_control: 7,         // LOW — CON reform as supply-side, deregulatory approach; general market-oriented philosophy; no drug pricing or cost control positions found
      justice_policing_accountability: 8, // HIGH — "big law and order guy"; law enforcement pay raises; SB 44 (gang mandatory minimums); SB 63 (expanded cash bail)
      justice_sentencing_goals: 9,    // HIGH — SB 44 (5-year mandatory minimums for gang offenses, 10-year for recruiting minors); SB 63 (expanded cash bail to 30 offenses including 18 misdemeanors); death penalty for fentanyl dealers
      justice_firearms: 9,            // HIGH — explicitly opposed to any new gun restrictions; HB 1018 (Firearms Industry Nondiscrimination Act); $10K/year teacher carry stipend; NRA-ILA praise
      climate_ambition: 8,            // LOW — no climate legislation or statements; strong Trump alignment; family background in oil/petroleum (Jones Petroleum Company); complete absence of any pro-climate action; inferred from pattern
    },
    valueStances: {
      universalism: -0.5,   // Transgender sports/bathroom restrictions, immigration enforcement, CRT ban, no climate/environmental action; NAACP forum only via video
      benevolence: 0.4,     // Teacher and law enforcement pay raises, STEM scholarships, "every Georgian deserves access to care," property tax relief; data center conflict complicates framing
      tradition: 0.8,       // Biblical studies in schools, CRT ban, transgender sports ban, heartbeat abortion law support, TPUSA Act, sixth-generation Georgian identity emphasis
      conformity: -0.3,     // Signed false elector certificates after 2020; named "Unindicted Co-Conspirator Individual 8" in Fulton County RICO indictment; major anti-conformity action despite law-and-order rhetoric
      security: 0.7,        // Mandatory minimums for gang offenses, expanded cash bail, death penalty for fentanyl dealers, law enforcement pay raises; income tax elimination reduces economic safety net
      power: 0.6,           // $10M personal campaign loan; oil executive family background; data center project on family land (AG conflict accusation); income tax elimination benefits high earners; Trump endorsement
      achievement: 0.5,     // UGA football co-captain; founded insurance company; income tax elimination framing around individual economic potential; school choice empowering families
      hedonism: -0.3,       // 6-week abortion ban support, transgender rights restrictions, CRT curriculum controls
      stimulation: 0.2,     // Income tax elimination is genuinely radical (transformative for a state that always had income tax); TPUSA Act disruptive of educational norms; social conservatism pulls negative
      self_direction: 0.1,  // School choice as parental freedom, gun rights, income tax elimination; transgender restrictions, CRT bans limit teachers, abortion restrictions, TPUSA Act — breadth of social restrictions slightly outweighs economic liberty
    },
  },

  {
    id: 'chris-carr',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Chris Carr',
      ballotDisplay: 'Chris Carr',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 9,
    profileSummary: 'Three-term Georgia Attorney General and Kemp-wing establishment Republican; built a decade-long conservative record through multi-state coalition lawsuits against federal climate, healthcare, and immigration policies, combined with aggressive prosecution of gangs, trafficking, and opioid manufacturers. Campaigns on lowest-tax-burden-in-the-Southeast and safe-streets themes.',
    positions: [
      'Pledges lowest tax burden of any southeastern state — income, sales, property, fees, and business regulations all targeted',
      'Opposes full Medicaid expansion; supports Georgia Pathways (work-requirement Medicaid); joined lawsuit to invalidate ACA',
      'Led or joined 10+ multi-state lawsuits against federal climate and environmental regulations (SEC disclosure, EPA emissions, WOTUS, social cost of carbon)',
      'Created Gang Prosecution Unit (115+ convictions), Human Trafficking Prosecution Unit (200+ victims rescued), and Organized Retail Theft unit',
      'Proposed 8-part anti-corruption plan including felony self-enrichment, ban on self-dealing, and dedicated Public Corruption Unit',
    ],
    axisStances: {
      econ_safetynet: 8,              // HIGH — opposes full Medicaid expansion; supports work-requirement Pathways waiver; sued Biden to preserve work requirements; "largest tax increase in state history" framing
      econ_investment: 8,             // HIGH — "lowest tax burden of any state in the southeastern United States"; property tax caps; GDEcD record shows PPP comfort (prevents 9)
      health_coverage_model: 8,       // HIGH — joined ACA invalidation lawsuit (2019); explicitly opposes full Medicaid expansion; sued Biden to preserve Pathways work-requirement Medicaid; conditional state-directed backstop
      health_public_health: 7,        // MEDIUM — opposed vaccine/mask mandates (Head Start lawsuit); Opioid Task Force (enforcement against pharma, not treatment-first); opposed gender-affirming care funding
      housing_affordability_tools: 7, // LOW — property tax caps as housing affordability measure; free-market background; no rent control, public housing, or subsidy positions
      justice_policing_accountability: 8, // HIGH — 160+ sheriff endorsements; Gang Prosecution Unit, Human Trafficking Prosecution Unit, Organized Retail Theft unit; strongly pro-enforcement; no reform rhetoric
      justice_sentencing_goals: 7,    // MEDIUM — 115+ gang convictions; all rhetoric is prosecution-and-conviction focused; no rehabilitation, reentry, or sentencing alternatives found
      justice_firearms: 8,            // HIGH — NRA amicus brief (NRA v. James, 2020); filed amicus opposing Savannah gun ordinance; Georgia Gun Owners criticism calibrates as mainstream conservative pro-gun (not absolutist)
      climate_ambition: 9,            // HIGH — challenged Biden social cost of carbon EO; led 10-state SEC climate disclosure challenge; 24-state EPA oil/gas emissions challenge; 24-state power plant emissions challenge; led WOTUS challenge (won 2023)
      climate_energy_portfolio: 8,    // HIGH — actively shielded fossil fuel industry from EPA emissions regulation across oil/gas production and coal/gas power generation; no pro-renewables positions
      climate_permitting: 8,          // MEDIUM — WOTUS litigation and anti-federal-environmental-authority pattern favor reducing review burdens; "gross federal overreach" framing; state/local control emphasis
    },
    valueStances: {
      universalism: -0.5,   // 5+ anti-climate lawsuits, fought ACA expansion, opposed transgender protections (multiple lawsuits), defended SB 202; anti-trafficking work is positive universalist signal offset by overwhelming pattern
      benevolence: 0.4,     // Anti-trafficking unit (200+ victims rescued), gang prosecution (community safety), opioid settlements ($1B+), property tax relief, 84K+ jobs as GDEcD Commissioner
      tradition: 0.7,       // Defended 6-week abortion ban in court; personal belief abortion should be prohibited except to save mother's life; opposed transgender protections (multiple lawsuits); defended SB 202; established institutional norms
      conformity: 0.7,      // Declined to pursue 2020 election fraud case despite direct Trump phone pressure (Dec 8, 2020); upheld institutional norms at great personal cost; defends legal outcomes through proper AG channels
      security: 0.8,        // Public safety is the foundation of his AG tenure; 160+ sheriff endorsements; gang unit, trafficking unit, retail theft unit, opioid task force; "safe streets" brand; central value
      power: 0.4,           // GDEcD Commissioner facilitating corporate investment; "No. 1 state to do business"; policy positions favor corporate/high-income interests; anti-corruption platform cuts against pure power deference
      achievement: 0.5,     // Work-requirement Medicaid conditions aid on personal effort; GDEcD results measured ($14.4B, 84K+ jobs); campaign as competence-driven; free-market think tank philosophical grounding
      hedonism: -0.3,       // Defended 6-week abortion ban (restricts reproductive autonomy); multiple transgender protection lawsuits (restricts identity expression); "liberty" is economic freedom and gun rights, not lifestyle
      stimulation: -0.4,    // Classic institutional Kemp-wing continuity candidate; "we've kept Georgia the No. 1 state to do business" — preserving success, not disrupting; anti-corruption plan strengthens institutions not reimagines
      self_direction: 0.1,  // Opposed vaccine/mask mandates (+), gun rights through AG actions (+); defended 6-week abortion ban (-), multiple transgender rights lawsuits (-), supported SB 202 voting restrictions (-); near-zero net
    },
  },

  {
    id: 'brad-raffensperger',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Brad Raffensperger',
      ballotDisplay: 'Brad Raffensperger',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 10,
    profileSummary: 'Georgia Secretary of State and former two-term state legislator running for governor on an aggressive tax-cutting and law-and-order platform. Nationally known for refusing Trump\'s 2021 demand to overturn Georgia\'s election results, he campaigns on integrity and affordability while governing and running as a conventional fiscal and social conservative.',
    positions: [
      'Eliminate Georgia\'s state income tax entirely; cap property taxes at inflation rate; eliminate all taxes on retirement benefits',
      'Expand parental school choice via tax credits; purge "woke curriculums" from public schools',
      'Fund state-local-federal law enforcement partnerships for immigration enforcement; "restore law and order"',
      'Ban puberty blockers, gender-affirming surgery for minors, and transgender participation in women\'s sports',
      'Championed SB 202 (Election Integrity Act) and proposes REAL ID requirement for voting; refused Trump\'s 2020 pressure to overturn election',
    ],
    axisStances: {
      econ_safetynet: 7,              // MEDIUM — no safety net expansion proposals; affordability through job creation and tax cuts; senior property tax exemptions are targeted but limited
      econ_investment: 8,             // HIGH — comprehensive tax elimination agenda (income, retirement, closing costs, property caps) would dramatically reduce state revenue for public investment; doubled school security grants is modest offset
      econ_school_choice: 7,          // MEDIUM — explicitly supports expanding tax credits for parental school choice; doubled school security grants shows some continued public school investment; "purge woke curriculums"
      health_coverage_model: 7,       // LOW — "America has the best hospital coverage in the world. It's the affordability issue"; no Medicaid expansion position documented; market-based framing; detailed plan promised but not yet released
      health_cost_control: 7,         // LOW — acknowledges affordability as problem; no specific cost control mechanism stated; market-based framing; plan promised not yet released
      justice_policing_accountability: 8, // MEDIUM — "restore law and order"; state-federal law enforcement partnerships for deportation; doubled school security grants; sponsored human trafficking legislation; zero reform language
      justice_sentencing_goals: 7,    // LOW — general "restore law and order" framing suggests punishment/deterrence orientation; no specific sentencing positions found
      climate_energy_portfolio: 7,    // LOW — 2024 PSC election cancellation drew criticism from Georgia Conservation Voters ("attack on our democracy and our clean energy future"); served on Energy, Utilities and Telecommunications committee (2015-2018) but no specific positions
    },
    valueStances: {
      universalism: -0.3,   // Transgender healthcare bans, immigration enforcement, personhood bill (2016), RFRA-style vote, voter ID restrictions; 2020 election defense is genuine universalism signal offset by pattern
      benevolence: 0.4,     // Co-founded childcare center; childcare incentives; senior property tax relief; school security grants doubled; "tax-free zones for struggling communities"; bounded in-group benevolence
      tradition: 0.6,       // Sponsored personhood bill with no exceptions (2016); "all abortions should be illegal" (Georgia Life Alliance 2016); "purge woke curriculums"; transgender healthcare and athletic bans enforce traditional gender norms
      conformity: 0.8,      // Defining value: refused Trump's demand to overturn 2020 election at great personal cost (death threats, primary challenge, party censure attempt); deployed auditable paper ballots; testified under immunity; PSC election cancellation is notable contrary signal
      security: 0.7,        // "Make Georgia affordable and safe"; tax cuts as affordability protection; "restore law and order"; doubled school security grants; law enforcement partnerships; SB 202 and REAL ID as electoral security; comprehensive security orientation
      power: 0.2,           // Business background (multi-state construction firm, ~150 employees); corporate-friendly tax agenda; defied most powerful Republican at great cost; operates outside party power structure; business-oriented without active pursuit of concentrated authority
      achievement: 0.6,     // B.S. Civil Engineering, M.B.A.; Licensed PE, Structural Engineer, General Contractor; built Tendon Systems from startup to ~150 employees; co-founded childcare center; jobs-first philosophy
      hedonism: -0.3,       // Personhood bill restricts reproductive autonomy; transgender surgery/puberty blocker bans for minors; RFRA-style bill enables discrimination based on identity
      stimulation: -0.1,    // Stability and order-oriented; "Make Georgia affordable and safe"; "restore law and order" implies returning to prior state; 2020 defiance was preserving constitutional order; conventional Republican platform
      self_direction: 0.2,  // 2020 election defiance was most significant act of independent political judgment; school choice supports parental autonomy; transgender healthcare bans restrict individual medical self-direction (-); personhood bill restricts reproductive self-direction (-)
    },
  },

  {
    id: 'rick-jackson',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Rick Jackson',
      ballotDisplay: 'Rick Jackson',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 11,
    profileSummary: 'Healthcare billionaire and first-time candidate running as a self-funded MAGA outsider; platform centers on income tax elimination, Medicaid expansion opposition, DEI bans, and immigration enforcement.',
    positions: [
      'Pledges to cut Georgia\'s state income tax in half within 4 years and eliminate it within 8, with a freeze on property taxes',
      'Opposes Medicaid expansion despite being a healthcare industry billionaire',
      'Would ban DEI in state government, public universities, and schools and "criminalize reverse discrimination"',
      'Supports Georgia\'s 6-week abortion ban (LIFE Act) and says he would not change it',
      'Pledges to make Georgia "number one state for deporting criminal illegal immigrants"',
    ],
    axisStances: {
      // 5 axes scored — first-time candidate with no voting record
      econ_investment: 8,             // LOW — no public investment proposals; platform entirely structured around tax cuts and spending reduction; "use AI to eliminate wasteful spending"
      health_coverage_model: 8,       // MEDIUM — explicitly opposes Medicaid expansion; no alternative coverage proposal; maintain status quo position; multiple independent sources confirm
      econ_school_choice: 7,          // LOW — "parental authority in Georgia classrooms"; "purge schools of woke ideology"; sympathy with school choice movement but no explicit voucher/charter mechanism proposed
      justice_policing_accountability: 7, // LOW — "I grew up in places where law enforcement was the difference between safety and chaos"; general pro-law-enforcement values statement; no policy specifics
    },
    valueStances: {
      universalism: -0.5,   // Ban DEI programs, "criminalize reverse discrimination," aggressive immigration enforcement, opposition to Medicaid expansion covering vulnerable populations
      benevolence: 0.4,     // Genuine philanthropic record on foster care (championed and passed legislation for free college tuition for former foster youth); tuition freeze for public college; but opposes Medicaid expansion helping most vulnerable
      tradition: 0.7,       // Faith-based philanthropy, "entirely pro life," supports 6-week abortion law, anti-DEI as defense of traditional norms, "restore common sense and parental authority in classrooms"
      conformity: -0.1,     // Rule-of-law immigration enforcement and pro-law-enforcement framing (+); explicitly "outsider with nothing to lose," sued sitting Lt. Governor, avoids press (-); couldn't name a single Trump policy he disagrees with
      security: 0.6,        // Pro-law-enforcement from personal experience; immigration enforcement focus; property tax freeze protecting families from being "priced out of their homes"; personal narrative escaping unsafe environments
      power: 0.7,           // Billionaire self-funding $50M campaign; CEO of $3B company; "million dollar Trump donor"; ran ads in DC/Palm Beach to get Trump's personal attention; using personal wealth to bypass traditional political gatekeepers
      achievement: 0.7,     // Grew up in public housing, 5 foster homes, 13 schools, didn't finish college — built $3B company; self-made meritocracy story used as qualification for office; tuition freeze and foster youth support channel achievement
      hedonism: 0.0,        // Faith-based orientation suggests modest social conservatism; no explicit restrictive positions beyond abortion
      stimulation: 0.3,     // "Outsider with nothing to lose," $50M entry reshuffled primary, suing frontrunner, "AI to eliminate waste"; culturally conservative substance constrains overall disruption score
      self_direction: 0.1,  // Income tax elimination (economic liberty), parental authority over education (+); "criminalize reverse discrimination" (government policing thought/speech), pro-life position restricting reproductive autonomy, DEI ban restricting institutional speech (-)
    },
  },

  {
    id: 'clark-dean',
    contestId: 'GA-GOVERNOR-2026',
    name: {
      full: 'Clark Dean',
      ballotDisplay: 'Clark Dean',
    },
    party: 'Republican',
    incumbencyStatus: 'challenger',
    ballotOrder: 12,
    profileSummary: 'First-time candidate and Transwestern CRE executive running as a Kemp-continuity outsider; platform emphasizes affordability, healthcare access, and public-private partnerships but lacks specific policy commitments on most issues.',
    positions: [
      'Frames campaign around ASAP pillars: Affordability, Strength, Accessibility, Prosperity',
      'Repeatedly highlights maternal mortality and rural/urban healthcare access as priorities',
      'Champions public-private partnerships and workforce development for economic growth',
      'Explicitly positions as Kemp legacy successor with government efficiency critique',
    ],
    axisStances: {
      // Only 2 axes scored — first-time candidate with no voting record and aspirational-only platform
      econ_investment: 6,             // LOW — public-private partnerships and workforce development suggest moderate market-oriented approach; Kemp continuity framing; no specific spending proposals
      health_coverage_model: 6,       // LOW — calls for expanding healthcare access; rural communities and maternal mortality focus; no Medicaid expansion, ACA, or public insurance mechanism mentioned; Kemp-aligned market-oriented inference
    },
    valueStances: {
      universalism: 0.2,    // Carter Center board chair role; maternal mortality and "rural and urban" healthcare language; no environmental or international positions
      benevolence: 0.6,     // Shepherd Center chair-elect, YMCA Metro Atlanta chair, Rotary Club president, Cafe Momentum Atlanta (at-risk youth restaurant), Atlanta Opera; "put Georgia families first"
      tradition: 0.4,       // "Principled conservative," explicit Kemp legacy continuity; no disruptive-change rhetoric; tradition invoked instrumentally not through faith or social conservatism
      conformity: 0.3,      // Career in large institutional frameworks (corporate boards, civic organizations, nonprofit governance); not a norm-violator despite "outsider" label
      security: 0.3,        // ASAP framework names "Strength — safety, security, and efficient government" as a pillar; no specific public safety positions
      power: 0.2,           // Senior CRE executive, multiple board-level positions, Metro Atlanta Chamber; civic profile heavily oriented toward community service; polling at 1%
      achievement: 0.7,     // Harvard biomedical engineering; varsity football; built nationally recognized Transaction Sciences Group practice; "dream big and achieve bigger"; workforce development and prosperity; ASAP "Prosperity" pillar
      hedonism: 0.0,
      stimulation: 0.2,     // Some outsider/novelty rhetoric; biomedical engineering background suggesting innovation; Kemp continuity prevents meaningful stimulation score
      self_direction: 0.2,  // Independent-thinker framing; "prioritize solutions over politics"; cross-partisan Carter Center role; no civil liberties positions stated
    },
  },

];
